import { Question } from '../types';

export const artsQuestions: Question[] = [
  // Easy Arts Questions (1-17)
  {
    id: 'arts-1',
    category: 'arts',
    question: 'Who painted the Mona Lisa?',
    options: ['Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Michelangelo'],
    correctAnswer: 'Leonardo da Vinci',
    explanation: 'Leonardo da Vinci painted the Mona Lisa between 1503 and 1519.',
    difficulty: 'easy',
  },
  {
    id: 'arts-2',
    category: 'arts',
    question: 'What are the three primary colors?',
    options: ['Red, Blue, Yellow', 'Green, Purple, Orange', 'Black, White, Gray', 'Pink, Brown, Gold'],
    correctAnswer: 'Red, Blue, Yellow',
    explanation: 'Primary colors are colors that can be mixed to make other colors!',
    difficulty: 'easy',
  },
  {
    id: 'arts-3',
    category: 'arts',
    question: 'Which famous fairy tale was written by Hans Christian Andersen?',
    options: ['The Little Mermaid', 'Cinderella', 'Snow White', 'Sleeping Beauty'],
    correctAnswer: 'The Little Mermaid',
    explanation: 'Hans Christian Andersen wrote The Little Mermaid in 1837.',
    difficulty: 'easy',
  },
  {
    id: 'arts-4',
    category: 'arts',
    question: 'What type of art is made by folding paper?',
    options: ['Origami', 'Pottery', 'Painting', 'Sculpture'],
    correctAnswer: 'Origami',
    explanation: 'Origami is the Japanese art of paper folding.',
    difficulty: 'easy',
  },
  {
    id: 'arts-5',
    category: 'arts',
    question: 'Who wrote "Charlie and the Chocolate Factory"?',
    options: ['Roald Dahl', 'J.K. Rowling', 'Dr. Seuss', 'C.S. Lewis'],
    correctAnswer: 'Roald Dahl',
    explanation: 'Roald Dahl wrote this beloved children\'s book in 1964.',
    difficulty: 'easy',
  },
  {
    id: 'arts-6',
    category: 'arts',
    question: 'What instrument does a conductor use to direct an orchestra?',
    options: ['Baton', 'Violin', 'Trumpet', 'Piano'],
    correctAnswer: 'Baton',
    explanation: 'A conductor uses a thin stick called a baton to guide the orchestra.',
    difficulty: 'easy',
  },
  {
    id: 'arts-7',
    category: 'arts',
    question: 'Which Disney movie features a young lion named Simba?',
    options: ['The Lion King', 'Aladdin', 'Beauty and the Beast', 'Mulan'],
    correctAnswer: 'The Lion King',
    explanation: 'The Lion King tells the story of Simba, a young lion who becomes king.',
    difficulty: 'easy',
  },
  {
    id: 'arts-8',
    category: 'arts',
    question: 'What do you call a person who writes books?',
    options: ['Author', 'Painter', 'Singer', 'Actor'],
    correctAnswer: 'Author',
    explanation: 'An author is someone who writes books, stories, or other written works.',
    difficulty: 'easy',
  },
  {
    id: 'arts-9',
    category: 'arts',
    question: 'Which of these is a string instrument?',
    options: ['Violin', 'Drum', 'Flute', 'Trumpet'],
    correctAnswer: 'Violin',
    explanation: 'A violin is a string instrument played with a bow.',
    difficulty: 'easy',
  },
  {
    id: 'arts-10',
    category: 'arts',
    question: 'What color do you get when you mix blue and yellow?',
    options: ['Green', 'Purple', 'Orange', 'Brown'],
    correctAnswer: 'Green',
    explanation: 'When you mix blue and yellow paint, you get green!',
    difficulty: 'easy',
  },
  {
    id: 'arts-11',
    category: 'arts',
    question: 'Who wrote "The Cat in the Hat"?',
    options: ['Dr. Seuss', 'Roald Dahl', 'E.B. White', 'A.A. Milne'],
    correctAnswer: 'Dr. Seuss',
    explanation: 'Dr. Seuss wrote "The Cat in the Hat" in 1957.',
    difficulty: 'easy',
  },
  {
    id: 'arts-12',
    category: 'arts',
    question: 'What do you call a building where you can see paintings and sculptures?',
    options: ['Museum', 'Library', 'School', 'Theater'],
    correctAnswer: 'Museum',
    explanation: 'A museum is a place where art and other important objects are displayed.',
    difficulty: 'easy',
  },
  {
    id: 'arts-13',
    category: 'arts',
    question: 'Which of these is used to paint with water colors?',
    options: ['Brush', 'Pencil', 'Crayon', 'Marker'],
    correctAnswer: 'Brush',
    explanation: 'Artists use special brushes to paint with water colors.',
    difficulty: 'easy',
  },
  {
    id: 'arts-14',
    category: 'arts',
    question: 'What is the name of Harry Potter\'s school?',
    options: ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'],
    correctAnswer: 'Hogwarts',
    explanation: 'Hogwarts School of Witchcraft and Wizardry is where Harry Potter learns magic.',
    difficulty: 'easy',
  },
  {
    id: 'arts-15',
    category: 'arts',
    question: 'Which instrument has black and white keys?',
    options: ['Piano', 'Guitar', 'Drums', 'Flute'],
    correctAnswer: 'Piano',
    explanation: 'A piano has 88 keys, both black and white.',
    difficulty: 'easy',
  },
  {
    id: 'arts-16',
    category: 'arts',
    question: 'Who wrote "Winnie-the-Pooh"?',
    options: ['A.A. Milne', 'Beatrix Potter', 'E.B. White', 'C.S. Lewis'],
    correctAnswer: 'A.A. Milne',
    explanation: 'A.A. Milne created Winnie-the-Pooh and his friends in the Hundred Acre Wood.',
    difficulty: 'easy',
  },
  {
    id: 'arts-17',
    category: 'arts',
    question: 'What do you call a book with pictures that tells a story?',
    options: ['Comic Book', 'Dictionary', 'Cookbook', 'Atlas'],
    correctAnswer: 'Comic Book',
    explanation: 'Comic books tell stories using both pictures and words.',
    difficulty: 'easy',
  },
  {
    id: 'arts-18',
    category: 'arts',
    question: 'What color do you get when you mix red and blue?',
    options: ['Purple', 'Green', 'Orange', 'Brown'],
    correctAnswer: 'Purple',
    explanation: 'When you mix red and blue paint, you get purple!',
    difficulty: 'easy',
  },
  {
    id: 'arts-19',
    category: 'arts',
    question: 'Who wrote "Charlotte\'s Web"?',
    options: ['E.B. White', 'Roald Dahl', 'Dr. Seuss', 'C.S. Lewis'],
    correctAnswer: 'E.B. White',
    explanation: 'E.B. White wrote this beloved story about a pig named Wilbur and a spider named Charlotte.',
    difficulty: 'easy',
  },
  {
    id: 'arts-20',
    category: 'arts',
    question: 'Which of these is a wind instrument?',
    options: ['Flute', 'Guitar', 'Drums', 'Piano'],
    correctAnswer: 'Flute',
    explanation: 'A flute is a wind instrument that makes music when you blow across it.',
    difficulty: 'easy',
  },
  {
    id: 'arts-21',
    category: 'arts',
    question: 'What do artists use to mix their paints?',
    options: ['Palette', 'Canvas', 'Easel', 'Frame'],
    correctAnswer: 'Palette',
    explanation: 'Artists use a palette to mix different colors of paint.',
    difficulty: 'easy',
  },
  {
    id: 'arts-22',
    category: 'arts',
    question: 'Which Disney princess has a magical golden hair?',
    options: ['Rapunzel', 'Cinderella', 'Snow White', 'Ariel'],
    correctAnswer: 'Rapunzel',
    explanation: 'Rapunzel has magical golden hair that glows when she sings.',
    difficulty: 'easy',
  },
  {
    id: 'arts-23',
    category: 'arts',
    question: 'What do you call someone who acts in plays or movies?',
    options: ['Actor', 'Director', 'Writer', 'Producer'],
    correctAnswer: 'Actor',
    explanation: 'An actor is someone who performs roles in plays, movies, or TV shows.',
    difficulty: 'easy',
  },
  {
    id: 'arts-24',
    category: 'arts',
    question: 'What color do you get when you mix red and yellow?',
    options: ['Orange', 'Green', 'Purple', 'Brown'],
    correctAnswer: 'Orange',
    explanation: 'When you mix red and yellow paint, you get orange!',
    difficulty: 'easy',
  },
  {
    id: 'arts-25',
    category: 'arts',
    question: 'Who wrote "Green Eggs and Ham"?',
    options: ['Dr. Seuss', 'Roald Dahl', 'E.B. White', 'A.A. Milne'],
    correctAnswer: 'Dr. Seuss',
    explanation: 'Dr. Seuss wrote "Green Eggs and Ham" using only 50 different words!',
    difficulty: 'easy',
  },
  {
    id: 'arts-26',
    category: 'arts',
    question: 'What do you call a person who takes photographs?',
    options: ['Photographer', 'Painter', 'Sculptor', 'Author'],
    correctAnswer: 'Photographer',
    explanation: 'A photographer is someone who takes pictures with a camera.',
    difficulty: 'easy',
  },
  {
    id: 'arts-27',
    category: 'arts',
    question: 'Which of these is a percussion instrument?',
    options: ['Drum', 'Violin', 'Flute', 'Guitar'],
    correctAnswer: 'Drum',
    explanation: 'A drum is a percussion instrument that you hit to make music.',
    difficulty: 'easy',
  },
  {
    id: 'arts-28',
    category: 'arts',
    question: 'What do artists paint on?',
    options: ['Canvas', 'Palette', 'Brush', 'Easel'],
    correctAnswer: 'Canvas',
    explanation: 'Artists often paint on canvas, which is a special type of fabric.',
    difficulty: 'easy',
  },
  {
    id: 'arts-29',
    category: 'arts',
    question: 'Who is Mickey Mouse\'s girlfriend?',
    options: ['Minnie Mouse', 'Daisy Duck', 'Snow White', 'Cinderella'],
    correctAnswer: 'Minnie Mouse',
    explanation: 'Minnie Mouse has been Mickey Mouse\'s girlfriend since they were both created by Walt Disney.',
    difficulty: 'easy',
  },
  {
    id: 'arts-30',
    category: 'arts',
    question: 'What do you call a story with magic and fantasy?',
    options: ['Fairy Tale', 'Biography', 'Textbook', 'Dictionary'],
    correctAnswer: 'Fairy Tale',
    explanation: 'A fairy tale is a magical story often involving princes, princesses, and magical creatures.',
    difficulty: 'easy',
  },
  {
    id: 'arts-31',
    category: 'arts',
    question: 'Which of these tools do artists use to draw?',
    options: ['Pencil', 'Hammer', 'Scissors', 'Ruler'],
    correctAnswer: 'Pencil',
    explanation: 'Artists use pencils to sketch and draw their artwork.',
    difficulty: 'easy',
  },
  {
    id: 'arts-32',
    category: 'arts',
    question: 'What is the name of Woody\'s best friend in Toy Story?',
    options: ['Buzz Lightyear', 'Rex', 'Hamm', 'Slinky Dog'],
    correctAnswer: 'Buzz Lightyear',
    explanation: 'Buzz Lightyear is a space ranger toy who becomes Woody\'s best friend.',
    difficulty: 'easy',
  },
  {
    id: 'arts-33',
    category: 'arts',
    question: 'What do you call a group of musicians playing together?',
    options: ['Band', 'Team', 'Club', 'Class'],
    correctAnswer: 'Band',
    explanation: 'A band is a group of musicians who play music together.',
    difficulty: 'easy',
  },
  {
    id: 'arts-34',
    category: 'arts',
    question: 'Who wrote "The Gruffalo"?',
    options: ['Julia Donaldson', 'J.K. Rowling', 'Roald Dahl', 'Dr. Seuss'],
    correctAnswer: 'Julia Donaldson',
    explanation: 'Julia Donaldson wrote "The Gruffalo", a story about a clever mouse in the woods.',
    difficulty: 'easy',
  },
  {
    id: 'arts-35',
    category: 'arts',
    question: 'Which famous artist painted "The Starry Night"?',
    options: ['Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Claude Monet'],
    correctAnswer: 'Vincent van Gogh',
    explanation: 'Vincent van Gogh painted "The Starry Night" in 1889 while at an asylum in France.',
    difficulty: 'medium',
  },
  {
    id: 'arts-36',
    category: 'arts',
    question: 'What is the art of beautiful handwriting called?',
    options: ['Calligraphy', 'Typography', 'Graffiti', 'Origami'],
    correctAnswer: 'Calligraphy',
    explanation: 'Calligraphy is the art of producing decorative handwriting with special pens or brushes.',
    difficulty: 'medium',
  },
  {
    id: 'arts-37',
    category: 'arts',
    question: 'Who wrote "The Chronicles of Narnia"?',
    options: ['C.S. Lewis', 'J.R.R. Tolkien', 'J.K. Rowling', 'Roald Dahl'],
    correctAnswer: 'C.S. Lewis',
    explanation: 'C.S. Lewis wrote "The Chronicles of Narnia" series, starting with "The Lion, the Witch and the Wardrobe".',
    difficulty: 'medium',
  },
  {
    id: 'arts-38',
    category: 'arts',
    question: 'What type of paint dries the slowest?',
    options: ['Oil Paint', 'Watercolor', 'Acrylic', 'Tempera'],
    correctAnswer: 'Oil Paint',
    explanation: 'Oil paint takes the longest to dry because it contains natural oils that dry slowly.',
    difficulty: 'medium',
  },
  {
    id: 'arts-39',
    category: 'arts',
    question: 'Which musical instrument has 47 strings?',
    options: ['Harp', 'Piano', 'Guitar', 'Violin'],
    correctAnswer: 'Harp',
    explanation: 'A concert or pedal harp typically has 47 strings and 7 pedals.',
    difficulty: 'medium',
  },
  {
    id: 'arts-40',
    category: 'arts',
    question: 'What is the name of Harry Potter\'s owl?',
    options: ['Hedwig', 'Errol', 'Fawkes', 'Pigwidgeon'],
    correctAnswer: 'Hedwig',
    explanation: 'Hedwig was Harry Potter\'s snowy owl, given to him by Hagrid on his 11th birthday.',
    difficulty: 'medium',
  },
  {
    id: 'arts-41',
    category: 'arts',
    question: 'Which art movement is Salvador Dalí associated with?',
    options: ['Surrealism', 'Impressionism', 'Cubism', 'Pop Art'],
    correctAnswer: 'Surrealism',
    explanation: 'Salvador Dalí was a major figure in the Surrealist movement, known for his dreamlike paintings.',
    difficulty: 'medium',
  },
  {
    id: 'arts-42',
    category: 'arts',
    question: 'What is the highest female singing voice called?',
    options: ['Soprano', 'Alto', 'Mezzo-soprano', 'Contralto'],
    correctAnswer: 'Soprano',
    explanation: 'Soprano is the highest female voice type in classical music.',
    difficulty: 'medium',
  },
  {
    id: 'arts-43',
    category: 'arts',
    question: 'Who wrote "The Hobbit"?',
    options: ['J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'Philip Pullman'],
    correctAnswer: 'J.R.R. Tolkien',
    explanation: 'J.R.R. Tolkien wrote "The Hobbit" in 1937, before "The Lord of the Rings".',
    difficulty: 'medium',
  },
  {
    id: 'arts-44',
    category: 'arts',
    question: 'What are the three secondary colors?',
    options: ['Green, Purple, Orange', 'Red, Blue, Yellow', 'Black, White, Gray', 'Pink, Brown, Gold'],
    correctAnswer: 'Green, Purple, Orange',
    explanation: 'Secondary colors are made by mixing two primary colors: blue+yellow=green, red+blue=purple, red+yellow=orange.',
    difficulty: 'medium',
  },
  {
    id: 'arts-45',
    category: 'arts',
    question: 'Which famous composer was deaf?',
    options: ['Beethoven', 'Mozart', 'Bach', 'Tchaikovsky'],
    correctAnswer: 'Beethoven',
    explanation: 'Ludwig van Beethoven began losing his hearing in his late 20s but continued to compose music.',
    difficulty: 'medium',
  },
  {
    id: 'arts-46',
    category: 'arts',
    question: 'What type of art involves making images by sticking colored pieces of paper together?',
    options: ['Collage', 'Mosaic', 'Origami', 'Sculpture'],
    correctAnswer: 'Collage',
    explanation: 'A collage is artwork created by sticking various materials, especially paper, onto a surface.',
    difficulty: 'medium',
  },
  {
    id: 'arts-47',
    category: 'arts',
    question: 'Who painted the ceiling of the Sistine Chapel?',
    options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
    correctAnswer: 'Michelangelo',
    explanation: 'Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512.',
    difficulty: 'medium',
  },
  {
    id: 'arts-48',
    category: 'arts',
    question: 'What is the main instrument in a string quartet?',
    options: ['Violin', 'Cello', 'Viola', 'Bass'],
    correctAnswer: 'Violin',
    explanation: 'A string quartet typically has two violins, one viola, and one cello.',
    difficulty: 'medium',
  },
  {
    id: 'arts-49',
    category: 'arts',
    question: 'Who wrote "Alice\'s Adventures in Wonderland"?',
    options: ['Lewis Carroll', 'J.M. Barrie', 'A.A. Milne', 'Beatrix Potter'],
    correctAnswer: 'Lewis Carroll',
    explanation: 'Lewis Carroll wrote "Alice\'s Adventures in Wonderland" in 1865.',
    difficulty: 'medium',
  },
  {
    id: 'arts-50',
    category: 'arts',
    question: 'What style of painting tries to capture the effects of light?',
    options: ['Impressionism', 'Cubism', 'Surrealism', 'Pop Art'],
    correctAnswer: 'Impressionism',
    explanation: 'Impressionist artists like Monet focused on capturing the changing effects of light.',
    difficulty: 'medium',
  },
  {
    id: 'arts-51',
    category: 'arts',
    question: 'Which Disney movie features a young mermaid who wants to become human?',
    options: ['The Little Mermaid', 'Beauty and the Beast', 'Cinderella', 'Snow White'],
    correctAnswer: 'The Little Mermaid',
    explanation: 'The Little Mermaid tells the story of Ariel, a mermaid princess who dreams of becoming human.',
    difficulty: 'medium',
  },
  {
    id: 'arts-52',
    category: 'arts',
    question: 'What is the art of creating designs with small colored tiles called?',
    options: ['Mosaic', 'Collage', 'Fresco', 'Tapestry'],
    correctAnswer: 'Mosaic',
    explanation: 'A mosaic is created by arranging small pieces of colored stone, glass, or tile.',
    difficulty: 'medium',
  },
  {
    id: 'arts-53',
    category: 'arts',
    question: 'Who composed "The Four Seasons"?',
    options: ['Vivaldi', 'Mozart', 'Bach', 'Beethoven'],
    correctAnswer: 'Vivaldi',
    explanation: 'Antonio Vivaldi composed "The Four Seasons" in 1723.',
    difficulty: 'medium',
  },
  {
    id: 'arts-54',
    category: 'arts',
    question: 'What is the name of the boy who never grows up in Peter Pan?',
    options: ['Peter Pan', 'Captain Hook', 'Wendy', 'John'],
    correctAnswer: 'Peter Pan',
    explanation: 'Peter Pan is the main character who lives in Neverland and refuses to grow up.',
    difficulty: 'medium',
  },
  {
    id: 'arts-55',
    category: 'arts',
    question: 'Which artist is known for painting soup cans?',
    options: ['Andy Warhol', 'Pablo Picasso', 'Salvador Dalí', 'Roy Lichtenstein'],
    correctAnswer: 'Andy Warhol',
    explanation: 'Andy Warhol created the famous Campbell\'s Soup Cans artwork in 1962.',
    difficulty: 'medium',
  },
  {
    id: 'arts-56',
    category: 'arts',
    question: 'What is a painting done on wet plaster called?',
    options: ['Fresco', 'Tempera', 'Gouache', 'Watercolor'],
    correctAnswer: 'Fresco',
    explanation: 'A fresco is created by painting on wet plaster, allowing the paint to become part of the wall.',
    difficulty: 'medium',
  },
  {
    id: 'arts-57',
    category: 'arts',
    question: 'Who wrote "The Tale of Peter Rabbit"?',
    options: ['Beatrix Potter', 'A.A. Milne', 'E.B. White', 'Kenneth Grahame'],
    correctAnswer: 'Beatrix Potter',
    explanation: 'Beatrix Potter wrote and illustrated "The Tale of Peter Rabbit" in 1902.',
    difficulty: 'medium',
  },
  {
    id: 'arts-58',
    category: 'arts',
    question: 'What type of dance tells a story without words?',
    options: ['Ballet', 'Hip Hop', 'Jazz', 'Tap'],
    correctAnswer: 'Ballet',
    explanation: 'Ballet uses dance and music to tell stories through movement without words.',
    difficulty: 'medium',
  },
  {
    id: 'arts-59',
    category: 'arts',
    question: 'Which famous painting shows a woman with a mysterious smile?',
    options: ['Mona Lisa', 'The Scream', 'Girl with a Pearl Earring', 'American Gothic'],
    correctAnswer: 'Mona Lisa',
    explanation: 'The Mona Lisa is famous for the subject\'s mysterious, subtle smile.',
    difficulty: 'medium',
  },
  {
    id: 'arts-60',
    category: 'arts',
    question: 'What is the lowest male singing voice called?',
    options: ['Bass', 'Tenor', 'Baritone', 'Alto'],
    correctAnswer: 'Bass',
    explanation: 'Bass is the lowest male voice type in classical music.',
    difficulty: 'medium',
  },
  {
    id: 'arts-61',
    category: 'arts',
    question: 'Who wrote "The Wind in the Willows"?',
    options: ['Kenneth Grahame', 'Beatrix Potter', 'A.A. Milne', 'E. Nesbit'],
    correctAnswer: 'Kenneth Grahame',
    explanation: 'Kenneth Grahame wrote "The Wind in the Willows" in 1908.',
    difficulty: 'medium',
  },
  {
    id: 'arts-62',
    category: 'arts',
    question: 'What do you call art that uses light as the main medium?',
    options: ['Light Art', 'Neon Art', 'Illumination', 'Photography'],
    correctAnswer: 'Light Art',
    explanation: 'Light art is created using light as the main artistic medium.',
    difficulty: 'medium',
  },
  {
    id: 'arts-63',
    category: 'arts',
    question: 'Which instrument is known as the "King of Instruments"?',
    options: ['Organ', 'Piano', 'Violin', 'Trumpet'],
    correctAnswer: 'Organ',
    explanation: 'The pipe organ is called the "King of Instruments" due to its size and complexity.',
    difficulty: 'medium',
  },
  {
    id: 'arts-64',
    category: 'arts',
    question: 'What is the main character\'s name in "The Jungle Book"?',
    options: ['Mowgli', 'Baloo', 'Bagheera', 'Shere Khan'],
    correctAnswer: 'Mowgli',
    explanation: 'Mowgli is the human boy raised by wolves in "The Jungle Book".',
    difficulty: 'medium',
  },
  {
    id: 'arts-65',
    category: 'arts',
    question: 'Which artist is famous for painting water lilies?',
    options: ['Claude Monet', 'Vincent van Gogh', 'Pablo Picasso', 'Salvador Dalí'],
    correctAnswer: 'Claude Monet',
    explanation: 'Claude Monet created many paintings of water lilies in his garden at Giverny.',
    difficulty: 'medium',
  },
  {
    id: 'arts-66',
    category: 'arts',
    question: 'What is a person who writes music called?',
    options: ['Composer', 'Conductor', 'Musician', 'Producer'],
    correctAnswer: 'Composer',
    explanation: 'A composer is someone who writes and creates musical compositions.',
    difficulty: 'medium',
  },
  {
    id: 'arts-67',
    category: 'arts',
    question: 'Who wrote "Where the Wild Things Are"?',
    options: ['Maurice Sendak', 'Dr. Seuss', 'Eric Carle', 'Shel Silverstein'],
    correctAnswer: 'Maurice Sendak',
    explanation: 'Maurice Sendak wrote and illustrated "Where the Wild Things Are" in 1963.',
    difficulty: 'medium',
  },
  {
    id: 'arts-68',
    category: 'arts',
    question: 'Which Renaissance artist sculpted the David statue?',
    options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'],
    correctAnswer: 'Michelangelo',
    explanation: 'Michelangelo carved the David statue from marble between 1501 and 1504.',
    difficulty: 'hard',
  },
  {
    id: 'arts-69',
    category: 'arts',
    question: 'What is the technique of painting on freshly laid wet lime plaster?',
    options: ['Buon Fresco', 'Tempera', 'Impasto', 'Sfumato'],
    correctAnswer: 'Buon Fresco',
    explanation: 'Buon fresco is the technique of painting on fresh, wet lime plaster, allowing the paint to become part of the wall.',
    difficulty: 'hard',
  },
  {
    id: 'arts-70',
    category: 'arts',
    question: 'Who composed the opera "The Marriage of Figaro"?',
    options: ['Mozart', 'Beethoven', 'Bach', 'Handel'],
    correctAnswer: 'Mozart',
    explanation: 'Wolfgang Amadeus Mozart composed "The Marriage of Figaro" in 1786.',
    difficulty: 'hard',
  },
  {
    id: 'arts-71',
    category: 'arts',
    question: 'Which art movement did Pablo Picasso help develop?',
    options: ['Cubism', 'Impressionism', 'Surrealism', 'Pop Art'],
    correctAnswer: 'Cubism',
    explanation: 'Pablo Picasso and Georges Braque developed Cubism in the early 20th century.',
    difficulty: 'hard',
  },
  {
    id: 'arts-72',
    category: 'arts',
    question: 'What is the name of the Greek Muse of Dance?',
    options: ['Terpsichore', 'Calliope', 'Thalia', 'Euterpe'],
    correctAnswer: 'Terpsichore',
    explanation: 'Terpsichore was one of the nine Muses in Greek mythology, specifically the Muse of Dance.',
    difficulty: 'hard',
  },
  {
    id: 'arts-73',
    category: 'arts',
    question: 'Who wrote the play "A Midsummer Night\'s Dream"?',
    options: ['William Shakespeare', 'Christopher Marlowe', 'Ben Jonson', 'John Webster'],
    correctAnswer: 'William Shakespeare',
    explanation: 'William Shakespeare wrote "A Midsummer Night\'s Dream" around 1595-1596.',
    difficulty: 'hard',
  },
  {
    id: 'arts-74',
    category: 'arts',
    question: 'What is the art of designing and creating stained glass windows called?',
    options: ['Glaziery', 'Glasswork', 'Vitrography', 'Fenestration'],
    correctAnswer: 'Glaziery',
    explanation: 'Glaziery is the art of cutting, fitting, and assembling colored glass to create stained glass windows.',
    difficulty: 'hard',
  },
  {
    id: 'arts-75',
    category: 'arts',
    question: 'Which Dutch artist painted "The Night Watch"?',
    options: ['Rembrandt', 'Vermeer', 'Van Gogh', 'Frans Hals'],
    correctAnswer: 'Rembrandt',
    explanation: 'Rembrandt van Rijn painted "The Night Watch" in 1642.',
    difficulty: 'hard',
  },
  {
    id: 'arts-76',
    category: 'arts',
    question: 'What is the term for a painting of everyday objects arranged in a pleasing way?',
    options: ['Still Life', 'Portrait', 'Landscape', 'Genre Scene'],
    correctAnswer: 'Still Life',
    explanation: 'A still life is an artwork depicting inanimate objects, such as fruit, flowers, or household items.',
    difficulty: 'hard',
  },
  {
    id: 'arts-77',
    category: 'arts',
    question: 'Who composed "The Nutcracker" ballet?',
    options: ['Tchaikovsky', 'Stravinsky', 'Prokofiev', 'Rimsky-Korsakov'],
    correctAnswer: 'Tchaikovsky',
    explanation: 'Pyotr Ilyich Tchaikovsky composed "The Nutcracker" ballet in 1892.',
    difficulty: 'hard',
  },
  {
    id: 'arts-78',
    category: 'arts',
    question: 'What is the Japanese art of paper folding called?',
    options: ['Origami', 'Kirigami', 'Ikebana', 'Bonsai'],
    correctAnswer: 'Origami',
    explanation: 'Origami is the traditional Japanese art of paper folding to create various designs.',
    difficulty: 'hard',
  },
  {
    id: 'arts-79',
    category: 'arts',
    question: 'Which artist painted "The Persistence of Memory" with melting clocks?',
    options: ['Salvador Dalí', 'Pablo Picasso', 'René Magritte', 'Joan Miró'],
    correctAnswer: 'Salvador Dalí',
    explanation: 'Salvador Dalí painted "The Persistence of Memory" in 1931, featuring surreal melting clocks.',
    difficulty: 'hard',
  },
  {
    id: 'arts-80',
    category: 'arts',
    question: 'What is the highest male singing voice called?',
    options: ['Countertenor', 'Tenor', 'Baritone', 'Bass'],
    correctAnswer: 'Countertenor',
    explanation: 'A countertenor is the highest male voice type, singing in a range similar to female alto.',
    difficulty: 'hard',
  },
  {
    id: 'arts-81',
    category: 'arts',
    question: 'Who painted "The Birth of Venus"?',
    options: ['Sandro Botticelli', 'Leonardo da Vinci', 'Raphael', 'Titian'],
    correctAnswer: 'Sandro Botticelli',
    explanation: 'Sandro Botticelli painted "The Birth of Venus" around 1485.',
    difficulty: 'hard',
  },
  {
    id: 'arts-82',
    category: 'arts',
    question: 'What is the art of arranging flowers called in Japanese culture?',
    options: ['Ikebana', 'Origami', 'Bonsai', 'Kintsugi'],
    correctAnswer: 'Ikebana',
    explanation: 'Ikebana is the Japanese art of flower arrangement, emphasizing form and balance.',
    difficulty: 'hard',
  },
  {
    id: 'arts-83',
    category: 'arts',
    question: 'Who wrote the novel "The Little Prince"?',
    options: ['Antoine de Saint-Exupéry', 'Jules Verne', 'Victor Hugo', 'Albert Camus'],
    correctAnswer: 'Antoine de Saint-Exupéry',
    explanation: 'Antoine de Saint-Exupéry wrote "The Little Prince" in 1943.',
    difficulty: 'hard',
  },
  {
    id: 'arts-84',
    category: 'arts',
    question: 'What is the technique of creating images by cutting and pasting materials called?',
    options: ['Collage', 'Montage', 'Assemblage', 'Decoupage'],
    correctAnswer: 'Collage',
    explanation: 'Collage is the technique of creating artwork by gluing various materials onto a surface.',
    difficulty: 'hard',
  },
  {
    id: 'arts-85',
    category: 'arts',
    question: 'What is the Japanese art of repairing broken pottery with gold called?',
    options: ['Kintsugi', 'Origami', 'Ikebana', 'Bonsai'],
    correctAnswer: 'Kintsugi',
    explanation: 'Kintsugi is the Japanese art of repairing broken pottery by mending areas of breakage with lacquer dusted or mixed with powdered gold.',
    difficulty: 'hard',
  },
  {
    id: 'arts-86',
    category: 'arts',
    question: 'Who painted "The Scream"?',
    options: ['Edvard Munch', 'Vincent van Gogh', 'Gustav Klimt', 'Claude Monet'],
    correctAnswer: 'Edvard Munch',
    explanation: 'Edvard Munch painted "The Scream" in 1893, expressing anxiety and existential dread.',
    difficulty: 'hard',
  },
  {
    id: 'arts-87',
    category: 'arts',
    question: 'What is the art of growing and training miniature trees called?',
    options: ['Bonsai', 'Ikebana', 'Topiary', 'Arborsculpture'],
    correctAnswer: 'Bonsai',
    explanation: 'Bonsai is the Japanese art of growing and training miniature trees in containers.',
    difficulty: 'hard',
  },
  {
    id: 'arts-88',
    category: 'arts',
    question: 'Who composed "Symphony No. 5" with its famous "fate knocking at the door" opening?',
    options: ['Beethoven', 'Mozart', 'Bach', 'Tchaikovsky'],
    correctAnswer: 'Beethoven',
    explanation: 'Ludwig van Beethoven composed Symphony No. 5 between 1804 and 1808.',
    difficulty: 'hard',
  },
  {
    id: 'arts-89',
    category: 'arts',
    question: 'What is the technique of painting with egg yolk and pigments called?',
    options: ['Tempera', 'Fresco', 'Encaustic', 'Gouache'],
    correctAnswer: 'Tempera',
    explanation: 'Tempera painting uses colored pigments mixed with egg yolk as a binder.',
    difficulty: 'hard',
  },
  {
    id: 'arts-90',
    category: 'arts',
    question: 'Who wrote "The Canterbury Tales"?',
    options: ['Geoffrey Chaucer', 'William Shakespeare', 'John Milton', 'Edmund Spenser'],
    correctAnswer: 'Geoffrey Chaucer',
    explanation: 'Geoffrey Chaucer wrote "The Canterbury Tales" in the late 14th century.',
    difficulty: 'hard',
  },
  {
    id: 'arts-91',
    category: 'arts',
    question: 'What is the art of carving or sculpting hedges and trees called?',
    options: ['Topiary', 'Bonsai', 'Arborsculpture', 'Espalier'],
    correctAnswer: 'Topiary',
    explanation: 'Topiary is the art of trimming and training plants into decorative shapes.',
    difficulty: 'hard',
  },
  {
    id: 'arts-92',
    category: 'arts',
    question: 'Which artist painted "Girl with a Pearl Earring"?',
    options: ['Johannes Vermeer', 'Rembrandt', 'Frans Hals', 'Jan Steen'],
    correctAnswer: 'Johannes Vermeer',
    explanation: 'Johannes Vermeer painted "Girl with a Pearl Earring" around 1665.',
    difficulty: 'hard',
  },
  {
    id: 'arts-93',
    category: 'arts',
    question: 'What is the art of beautiful writing in Arabic called?',
    options: ['Arabic Calligraphy', 'Kufic Script', 'Naskh', 'Diwani'],
    correctAnswer: 'Arabic Calligraphy',
    explanation: 'Arabic Calligraphy is the artistic practice of handwriting Arabic script in a fluid manner.',
    difficulty: 'hard',
  },
  {
    id: 'arts-94',
    category: 'arts',
    question: 'Who wrote the epic poem "Paradise Lost"?',
    options: ['John Milton', 'Geoffrey Chaucer', 'William Shakespeare', 'Edmund Spenser'],
    correctAnswer: 'John Milton',
    explanation: 'John Milton wrote "Paradise Lost", an epic poem about the Fall of Man, published in 1667.',
    difficulty: 'hard',
  },
  {
    id: 'arts-95',
    category: 'arts',
    question: 'What is the technique of painting with hot wax called?',
    options: ['Encaustic', 'Tempera', 'Fresco', 'Impasto'],
    correctAnswer: 'Encaustic',
    explanation: 'Encaustic painting uses heated beeswax mixed with colored pigments.',
    difficulty: 'hard',
  },
  {
    id: 'arts-96',
    category: 'arts',
    question: 'Which composer wrote "The Four Seasons"?',
    options: ['Antonio Vivaldi', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven'],
    correctAnswer: 'Antonio Vivaldi',
    explanation: 'Antonio Vivaldi composed "The Four Seasons" violin concertos in 1723.',
    difficulty: 'hard',
  },
  {
    id: 'arts-97',
    category: 'arts',
    question: 'What is the art of paper cutting called in Chinese culture?',
    options: ['Jianzhi', 'Origami', 'Kirigami', 'Papercutting'],
    correctAnswer: 'Jianzhi',
    explanation: 'Jianzhi is the Chinese art of paper cutting, used for decorative purposes.',
    difficulty: 'hard',
  },
  {
    id: 'arts-98',
    category: 'arts',
    question: 'Who painted "The Garden of Earthly Delights"?',
    options: ['Hieronymus Bosch', 'Pieter Bruegel', 'Jan van Eyck', 'Albrecht Dürer'],
    correctAnswer: 'Hieronymus Bosch',
    explanation: 'Hieronymus Bosch painted "The Garden of Earthly Delights" between 1490 and 1510.',
    difficulty: 'hard',
  },
  {
    id: 'arts-99',
    category: 'arts',
    question: 'What is the traditional Korean art of paper making called?',
    options: ['Hanji', 'Washi', 'Xuan', 'Mulberry'],
    correctAnswer: 'Hanji',
    explanation: 'Hanji is the traditional Korean art of making handmade paper from mulberry trees.',
    difficulty: 'hard',
  },
  {
    id: 'arts-100',
    category: 'arts',
    question: 'Who designed the Sagrada Familia basilica in Barcelona?',
    options: ['Antoni Gaudí', 'Frank Lloyd Wright', 'Le Corbusier', 'Frank Gehry'],
    correctAnswer: 'Antoni Gaudí',
    explanation: 'Antoni Gaudí designed the Sagrada Familia, which began construction in 1882 and is still unfinished.',
    difficulty: 'hard',
  }
]; 