import { Question } from '../types';

export const historyQuestions: Question[] = [
  // Easy History Questions (34)
  {
    id: 'history-1',
    category: 'history',
    question: 'Who was the first President of the United States?',
    options: ['George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'John Adams'],
    correctAnswer: 'George Washington',
    explanation: 'George Washington served as the first President from 1789 to 1797.',
    difficulty: 'easy',
  },
  {
    id: 'history-2',
    category: 'history',
    question: 'Which ancient civilization built the pyramids?',
    options: ['Egyptians', 'Romans', 'Greeks', 'Chinese'],
    correctAnswer: 'Egyptians',
    explanation: 'The ancient Egyptians built the pyramids as tombs for their pharaohs!',
    difficulty: 'easy',
  },
  {
    id: 'history-3',
    category: 'history',
    question: 'What famous wall was built in China to keep out invaders?',
    options: ['Great Wall', 'Stone Wall', 'Brick Wall', 'High Wall'],
    correctAnswer: 'Great Wall',
    explanation: 'The Great Wall of China is over 13,000 miles long!',
    difficulty: 'easy',
  },
  {
    id: 'history-4',
    category: 'history',
    question: 'On which continent did the Roman Empire begin?',
    options: ['Europe', 'Asia', 'Africa', 'South America'],
    correctAnswer: 'Europe',
    explanation: 'The Roman Empire began in Rome, Italy, which is in Europe!',
    difficulty: 'easy',
  },
  {
    id: 'history-5',
    category: 'history',
    question: 'What ocean did Christopher Columbus cross to reach America?',
    options: ['Atlantic', 'Pacific', 'Indian', 'Arctic'],
    correctAnswer: 'Atlantic',
    explanation: 'Columbus crossed the Atlantic Ocean in 1492!',
    difficulty: 'easy',
  },
  {
    id: 'history-6',
    category: 'history',
    question: 'Which famous ship sank on its first voyage in 1912?',
    options: ['Titanic', 'Queen Mary', 'Mayflower', 'Santa Maria'],
    correctAnswer: 'Titanic',
    explanation: 'The Titanic sank after hitting an iceberg on April 15, 1912!',
    difficulty: 'easy',
  },
  {
    id: 'history-7',
    category: 'history',
    question: 'Who was the first woman to fly solo across the Atlantic Ocean?',
    options: ['Amelia Earhart', 'Marie Curie', 'Helen Keller', 'Rosa Parks'],
    correctAnswer: 'Amelia Earhart',
    explanation: 'Amelia Earhart made this historic flight in 1932!',
    difficulty: 'easy',
  },
  {
    id: 'history-8',
    category: 'history',
    question: 'What was the name of the first successful English colony in America?',
    options: ['Jamestown', 'Plymouth', 'Boston', 'New York'],
    correctAnswer: 'Jamestown',
    explanation: 'Jamestown was established in 1607 in what is now Virginia!',
    difficulty: 'easy',
  },
  {
    id: 'history-9',
    category: 'history',
    question: 'Who painted the Mona Lisa?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Pablo Picasso', 'Vincent van Gogh'],
    correctAnswer: 'Leonardo da Vinci',
    explanation: 'Leonardo da Vinci painted the Mona Lisa in the early 1500s!',
    difficulty: 'easy',
  },
  {
    id: 'history-10',
    category: 'history',
    question: 'What ancient wonder was a lighthouse in Egypt?',
    options: ['Lighthouse of Alexandria', 'Colossus of Rhodes', 'Hanging Gardens', 'Great Pyramid'],
    correctAnswer: 'Lighthouse of Alexandria',
    explanation: 'The Lighthouse of Alexandria was one of the Seven Wonders of the Ancient World!',
    difficulty: 'easy',
  },
  {
    id: 'history-11',
    category: 'history',
    question: 'Who was the first person to walk on the moon?',
    options: ['Neil Armstrong', 'Buzz Aldrin', 'John Glenn', 'Yuri Gagarin'],
    correctAnswer: 'Neil Armstrong',
    explanation: 'Neil Armstrong took his "one small step" on July 20, 1969!',
    difficulty: 'easy',
  },
  {
    id: 'history-12',
    category: 'history',
    question: 'What was the capital of the Inca Empire?',
    options: ['Cusco', 'Lima', 'Quito', 'Machu Picchu'],
    correctAnswer: 'Cusco',
    explanation: 'Cusco was the capital of the Inca Empire in what is now Peru!',
    difficulty: 'easy',
  },
  {
    id: 'history-13',
    category: 'history',
    question: 'Which continent was home to the first Olympic Games?',
    options: ['Europe', 'Asia', 'Africa', 'North America'],
    correctAnswer: 'Europe',
    explanation: 'The first Olympic Games were held in Ancient Greece, in Europe!',
    difficulty: 'easy',
  },
  {
    id: 'history-14',
    category: 'history',
    question: 'What did the Wright brothers invent?',
    options: ['Airplane', 'Telephone', 'Light Bulb', 'Car'],
    correctAnswer: 'Airplane',
    explanation: 'The Wright brothers made the first powered flight in 1903!',
    difficulty: 'easy',
  },
  {
    id: 'history-15',
    category: 'history',
    question: 'Which famous document begins with "We the People"?',
    options: ['U.S. Constitution', 'Declaration of Independence', 'Bill of Rights', 'Magna Carta'],
    correctAnswer: 'U.S. Constitution',
    explanation: 'The U.S. Constitution begins with these famous words!',
    difficulty: 'easy',
  },
  {
    id: 'history-16',
    category: 'history',
    question: 'What was the name of Christopher Columbus\'s largest ship?',
    options: ['Santa Maria', 'Nina', 'Pinta', 'Mayflower'],
    correctAnswer: 'Santa Maria',
    explanation: 'The Santa Maria was the largest of Columbus\'s three ships!',
    difficulty: 'easy',
  },
  {
    id: 'history-17',
    category: 'history',
    question: 'Which civilization built Machu Picchu?',
    options: ['Inca', 'Maya', 'Aztec', 'Egyptian'],
    correctAnswer: 'Inca',
    explanation: 'The Inca built Machu Picchu around 1450 CE!',
    difficulty: 'easy',
  },
  {
    id: 'history-18',
    category: 'history',
    question: 'What ancient civilization used hieroglyphics?',
    options: ['Egyptians', 'Greeks', 'Romans', 'Chinese'],
    correctAnswer: 'Egyptians',
    explanation: 'The ancient Egyptians used hieroglyphics as their writing system!',
    difficulty: 'easy',
  },
  {
    id: 'history-19',
    category: 'history',
    question: 'Who invented the telephone?',
    options: ['Alexander Graham Bell', 'Thomas Edison', 'Benjamin Franklin', 'Albert Einstein'],
    correctAnswer: 'Alexander Graham Bell',
    explanation: 'Alexander Graham Bell invented the telephone in 1876!',
    difficulty: 'easy',
  },
  {
    id: 'history-20',
    category: 'history',
    question: 'What was the name of the first artificial satellite in space?',
    options: ['Sputnik 1', 'Explorer 1', 'Apollo 1', 'Voyager 1'],
    correctAnswer: 'Sputnik 1',
    explanation: 'Sputnik 1 was launched by the Soviet Union in 1957!',
    difficulty: 'easy',
  },
  {
    id: 'history-21',
    category: 'history',
    question: 'Which famous leader said "I have a dream"?',
    options: ['Martin Luther King Jr.', 'John F. Kennedy', 'Abraham Lincoln', 'George Washington'],
    correctAnswer: 'Martin Luther King Jr.',
    explanation: 'Martin Luther King Jr. gave his famous "I Have a Dream" speech in 1963!',
    difficulty: 'easy',
  },
  {
    id: 'history-22',
    category: 'history',
    question: 'What was the name of the first dog in space?',
    options: ['Laika', 'Rover', 'Spot', 'Rex'],
    correctAnswer: 'Laika',
    explanation: 'Laika was launched into space by the Soviet Union in 1957!',
    difficulty: 'easy',
  },
  {
    id: 'history-23',
    category: 'history',
    question: 'Which country gave the Statue of Liberty to the United States?',
    options: ['France', 'England', 'Italy', 'Spain'],
    correctAnswer: 'France',
    explanation: 'France gave the Statue of Liberty as a gift in 1886!',
    difficulty: 'easy',
  },
  {
    id: 'history-24',
    category: 'history',
    question: 'What was the name of the first computer?',
    options: ['ENIAC', 'Apple I', 'IBM PC', 'Commodore 64'],
    correctAnswer: 'ENIAC',
    explanation: 'ENIAC was completed in 1945 and was the first general-purpose electronic computer!',
    difficulty: 'easy',
  },
  {
    id: 'history-25',
    category: 'history',
    question: 'Who was the first European explorer to reach India by sea?',
    options: ['Vasco da Gama', 'Christopher Columbus', 'Marco Polo', 'Ferdinand Magellan'],
    correctAnswer: 'Vasco da Gama',
    explanation: 'Vasco da Gama reached India by sailing around Africa in 1498!',
    difficulty: 'easy',
  },
  {
    id: 'history-26',
    category: 'history',
    question: 'What was the first national park in the United States?',
    options: ['Yellowstone', 'Yosemite', 'Grand Canyon', 'Rocky Mountain'],
    correctAnswer: 'Yellowstone',
    explanation: 'Yellowstone became the first national park in 1872!',
    difficulty: 'easy',
  },
  {
    id: 'history-27',
    category: 'history',
    question: 'Which queen was known as "The Virgin Queen"?',
    options: ['Elizabeth I', 'Victoria', 'Mary I', 'Anne'],
    correctAnswer: 'Elizabeth I',
    explanation: 'Elizabeth I of England was called "The Virgin Queen" because she never married!',
    difficulty: 'easy',
  },
  {
    id: 'history-28',
    category: 'history',
    question: 'What was the first video game console?',
    options: ['Magnavox Odyssey', 'Atari 2600', 'Nintendo NES', 'Sega Genesis'],
    correctAnswer: 'Magnavox Odyssey',
    explanation: 'The Magnavox Odyssey was released in 1972!',
    difficulty: 'easy',
  },
  {
    id: 'history-29',
    category: 'history',
    question: 'Which city was the first capital of the United States?',
    options: ['New York City', 'Philadelphia', 'Washington D.C.', 'Boston'],
    correctAnswer: 'New York City',
    explanation: 'New York City was the first capital from 1789 to 1790!',
    difficulty: 'easy',
  },
  {
    id: 'history-30',
    category: 'history',
    question: 'What was the first animated feature film?',
    options: ['Snow White', 'Pinocchio', 'Bambi', 'Fantasia'],
    correctAnswer: 'Snow White',
    explanation: 'Snow White and the Seven Dwarfs was released by Disney in 1937!',
    difficulty: 'easy',
  },
  {
    id: 'history-31',
    category: 'history',
    question: 'Who invented the light bulb?',
    options: ['Thomas Edison', 'Alexander Graham Bell', 'Benjamin Franklin', 'Nikola Tesla'],
    correctAnswer: 'Thomas Edison',
    explanation: 'Thomas Edison invented the practical electric light bulb in 1879!',
    difficulty: 'easy',
  },
  {
    id: 'history-32',
    category: 'history',
    question: 'What was the first planet discovered using a telescope?',
    options: ['Uranus', 'Neptune', 'Mars', 'Venus'],
    correctAnswer: 'Uranus',
    explanation: 'William Herschel discovered Uranus in 1781!',
    difficulty: 'easy',
  },
  {
    id: 'history-33',
    category: 'history',
    question: 'Which civilization created the first written alphabet?',
    options: ['Phoenicians', 'Greeks', 'Romans', 'Egyptians'],
    correctAnswer: 'Phoenicians',
    explanation: 'The Phoenicians created the first true alphabet around 1050 BCE!',
    difficulty: 'easy',
  },
  {
    id: 'history-34',
    category: 'history',
    question: 'What was the first successful photograph?',
    options: ['View from Window', 'Portrait', 'Landscape', 'Still Life'],
    correctAnswer: 'View from Window',
    explanation: 'Joseph Nicéphore Niépce took the first successful photograph, "View from the Window at Le Gras," in 1826!',
    difficulty: 'easy',
  },
  // Medium History Questions (33)
  {
    id: 'history-35',
    category: 'history',
    question: 'Who wrote the Declaration of Independence?',
    options: ['Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'John Adams'],
    correctAnswer: 'Thomas Jefferson',
    explanation: 'Thomas Jefferson wrote the Declaration of Independence in 1776!',
    difficulty: 'medium',
  },
  {
    id: 'history-36',
    category: 'history',
    question: 'What was the name of the first successful powered aircraft?',
    options: ['Wright Flyer', 'Spirit of St. Louis', 'Kitty Hawk', 'Glider One'],
    correctAnswer: 'Wright Flyer',
    explanation: 'The Wright Flyer made its first flight on December 17, 1903!',
    difficulty: 'medium',
  },
  {
    id: 'history-37',
    category: 'history',
    question: 'Which empire was ruled by the Aztecs?',
    options: ['Mexican', 'Peruvian', 'Brazilian', 'Colombian'],
    correctAnswer: 'Mexican',
    explanation: 'The Aztec Empire ruled much of what is now central Mexico!',
    difficulty: 'medium',
  },
  {
    id: 'history-38',
    category: 'history',
    question: 'What was the first successful permanent English settlement in North America?',
    options: ['Jamestown', 'Plymouth', 'Roanoke', 'Massachusetts Bay'],
    correctAnswer: 'Jamestown',
    explanation: 'Jamestown was established in 1607 and became the first permanent English settlement!',
    difficulty: 'medium',
  },
  {
    id: 'history-39',
    category: 'history',
    question: 'Who was the first woman to win a Nobel Prize?',
    options: ['Marie Curie', 'Mother Teresa', 'Jane Addams', 'Pearl Buck'],
    correctAnswer: 'Marie Curie',
    explanation: 'Marie Curie won the Nobel Prize in Physics in 1903!',
    difficulty: 'medium',
  },
  {
    id: 'history-40',
    category: 'history',
    question: 'What was the capital of the Byzantine Empire?',
    options: ['Constantinople', 'Rome', 'Athens', 'Alexandria'],
    correctAnswer: 'Constantinople',
    explanation: 'Constantinople (now Istanbul) was the capital of the Byzantine Empire for over 1000 years!',
    difficulty: 'medium',
  },
  {
    id: 'history-41',
    category: 'history',
    question: 'Which pharaoh built the Great Pyramid of Giza?',
    options: ['Khufu', 'Tutankhamun', 'Ramesses II', 'Cleopatra'],
    correctAnswer: 'Khufu',
    explanation: 'The Great Pyramid was built as a tomb for Pharaoh Khufu around 2560 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-42',
    category: 'history',
    question: 'What was the first successful submarine to sink an enemy ship?',
    options: ['H.L. Hunley', 'Nautilus', 'U-boat', 'Holland VI'],
    correctAnswer: 'H.L. Hunley',
    explanation: 'The H.L. Hunley sank the USS Housatonic in 1864 during the Civil War!',
    difficulty: 'medium',
  },
  {
    id: 'history-43',
    category: 'history',
    question: 'Which civilization invented paper?',
    options: ['Chinese', 'Egyptian', 'Roman', 'Greek'],
    correctAnswer: 'Chinese',
    explanation: 'The Chinese invented paper around 105 CE during the Han Dynasty!',
    difficulty: 'medium',
  },
  {
    id: 'history-44',
    category: 'history',
    question: 'What was the first successful electric car?',
    options: ['Baker Electric', 'Tesla Model S', 'GM EV1', 'Nissan Leaf'],
    correctAnswer: 'Baker Electric',
    explanation: 'The Baker Electric car was first produced in 1899!',
    difficulty: 'medium',
  },
  {
    id: 'history-45',
    category: 'history',
    question: 'Which empire was known as "the empire on which the sun never sets"?',
    options: ['British Empire', 'Roman Empire', 'Spanish Empire', 'Mongol Empire'],
    correctAnswer: 'British Empire',
    explanation: 'The British Empire was so large that it was always daytime somewhere in its territories!',
    difficulty: 'medium',
  },
  {
    id: 'history-46',
    category: 'history',
    question: 'Who was the first European to discover Brazil?',
    options: ['Pedro Álvares Cabral', 'Christopher Columbus', 'Vasco da Gama', 'Amerigo Vespucci'],
    correctAnswer: 'Pedro Álvares Cabral',
    explanation: 'Pedro Álvares Cabral discovered Brazil in 1500!',
    difficulty: 'medium',
  },
  {
    id: 'history-47',
    category: 'history',
    question: 'What was the first successful vaccine?',
    options: ['Smallpox', 'Polio', 'Rabies', 'Measles'],
    correctAnswer: 'Smallpox',
    explanation: 'Edward Jenner developed the first successful vaccine against smallpox in 1796!',
    difficulty: 'medium',
  },
  {
    id: 'history-48',
    category: 'history',
    question: 'Which civilization built the city of Petra?',
    options: ['Nabataeans', 'Romans', 'Greeks', 'Persians'],
    correctAnswer: 'Nabataeans',
    explanation: 'The Nabataeans carved Petra out of rock around 312 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-49',
    category: 'history',
    question: 'What was the first successful heart transplant?',
    options: ['1967', '1955', '1972', '1980'],
    correctAnswer: '1967',
    explanation: 'Dr. Christiaan Barnard performed the first successful heart transplant in 1967!',
    difficulty: 'medium',
  },
  {
    id: 'history-50',
    category: 'history',
    question: 'Which civilization invented the concept of zero?',
    options: ['Indian', 'Arabic', 'Greek', 'Chinese'],
    correctAnswer: 'Indian',
    explanation: 'The concept of zero as a number was developed in ancient India!',
    difficulty: 'medium',
  },
  {
    id: 'history-51',
    category: 'history',
    question: 'What was the first successful space station?',
    options: ['Salyut 1', 'Skylab', 'Mir', 'ISS'],
    correctAnswer: 'Salyut 1',
    explanation: 'Salyut 1 was launched by the Soviet Union in 1971!',
    difficulty: 'medium',
  },
  {
    id: 'history-52',
    category: 'history',
    question: 'What was the first successful color photograph?',
    options: ['Tartan Ribbon', 'Landscape', 'Portrait', 'Still Life'],
    correctAnswer: 'Tartan Ribbon',
    explanation: 'James Clerk Maxwell created the first color photograph, "Tartan Ribbon," in 1861!',
    difficulty: 'medium',
  },
  {
    id: 'history-53',
    category: 'history',
    question: 'Which civilization built the first known library?',
    options: ['Sumerians', 'Egyptians', 'Greeks', 'Romans'],
    correctAnswer: 'Sumerians',
    explanation: 'The Sumerians built the first known library in Nippur around 2500 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-54',
    category: 'history',
    question: 'What was the first successful organ transplant?',
    options: ['Kidney', 'Heart', 'Liver', 'Lung'],
    correctAnswer: 'Kidney',
    explanation: 'The first successful organ transplant was a kidney transplant in 1954!',
    difficulty: 'medium',
  },
  {
    id: 'history-55',
    category: 'history',
    question: 'Which civilization invented the calendar?',
    options: ['Egyptians', 'Mayans', 'Romans', 'Chinese'],
    correctAnswer: 'Egyptians',
    explanation: 'The ancient Egyptians created the first known calendar around 3000 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-56',
    category: 'history',
    question: 'What was the first successful passenger airline?',
    options: ['DELAG', 'Pan Am', 'KLM', 'British Airways'],
    correctAnswer: 'DELAG',
    explanation: 'DELAG was the world\'s first airline to transport paying passengers in 1909!',
    difficulty: 'medium',
  },
  {
    id: 'history-57',
    category: 'history',
    question: 'Which civilization first used steel?',
    options: ['Hittites', 'Greeks', 'Romans', 'Chinese'],
    correctAnswer: 'Hittites',
    explanation: 'The Hittites were the first to make steel around 1400 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-58',
    category: 'history',
    question: 'What was the first successful anti-bacterial medicine?',
    options: ['Penicillin', 'Aspirin', 'Morphine', 'Quinine'],
    correctAnswer: 'Penicillin',
    explanation: 'Alexander Fleming discovered penicillin in 1928!',
    difficulty: 'medium',
  },
  {
    id: 'history-59',
    category: 'history',
    question: 'Which civilization invented concrete?',
    options: ['Romans', 'Greeks', 'Egyptians', 'Chinese'],
    correctAnswer: 'Romans',
    explanation: 'The Romans developed and perfected concrete around 300 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-60',
    category: 'history',
    question: 'What was the first successful credit card?',
    options: ['Diners Club', 'American Express', 'Visa', 'MasterCard'],
    correctAnswer: 'Diners Club',
    explanation: 'The Diners Club card was introduced in 1950!',
    difficulty: 'medium',
  },
  {
    id: 'history-61',
    category: 'history',
    question: 'Which civilization invented the wheel?',
    options: ['Sumerians', 'Egyptians', 'Indians', 'Chinese'],
    correctAnswer: 'Sumerians',
    explanation: 'The Sumerians invented the wheel around 3500 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-62',
    category: 'history',
    question: 'What was the first successful instant camera?',
    options: ['Polaroid', 'Kodak', 'Canon', 'Nikon'],
    correctAnswer: 'Polaroid',
    explanation: 'The first Polaroid instant camera was sold in 1948!',
    difficulty: 'medium',
  },
  {
    id: 'history-63',
    category: 'history',
    question: 'Which civilization invented glass?',
    options: ['Egyptians', 'Romans', 'Greeks', 'Persians'],
    correctAnswer: 'Egyptians',
    explanation: 'The Egyptians invented glass around 3500 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-64',
    category: 'history',
    question: 'What was the first successful video game?',
    options: ['Pong', 'Space Invaders', 'Pac-Man', 'Tennis for Two'],
    correctAnswer: 'Tennis for Two',
    explanation: 'Tennis for Two was created by William Higinbotham in 1958!',
    difficulty: 'medium',
  },
  {
    id: 'history-65',
    category: 'history',
    question: 'Which civilization invented soap?',
    options: ['Babylonians', 'Egyptians', 'Romans', 'Greeks'],
    correctAnswer: 'Babylonians',
    explanation: 'The Babylonians were making soap around 2800 BCE!',
    difficulty: 'medium',
  },
  {
    id: 'history-66',
    category: 'history',
    question: 'What was the first successful mobile phone call?',
    options: ['1973', '1983', '1965', '1990'],
    correctAnswer: '1973',
    explanation: 'The first mobile phone call was made by Martin Cooper of Motorola in 1973!',
    difficulty: 'medium',
  },
  {
    id: 'history-67',
    category: 'history',
    question: 'Which civilization invented the sundial?',
    options: ['Babylonians', 'Egyptians', 'Greeks', 'Chinese'],
    correctAnswer: 'Babylonians',
    explanation: 'The Babylonians invented the sundial around 1500 BCE!',
    difficulty: 'medium',
  },
  // Hard History Questions (33)
  {
    id: 'history-68',
    category: 'history',
    question: 'In which year did World War I begin?',
    options: ['1914', '1915', '1916', '1917'],
    correctAnswer: '1914',
    explanation: 'World War I began in 1914 and lasted until 1918.',
    difficulty: 'hard',
  },
  {
    id: 'history-69',
    category: 'history',
    question: 'Who was the first Emperor of China?',
    options: ['Qin Shi Huang', 'Han Wudi', 'Tang Taizong', 'Ming Hongwu'],
    correctAnswer: 'Qin Shi Huang',
    explanation: 'Qin Shi Huang unified China in 221 BCE and became its first Emperor!',
    difficulty: 'hard',
  },
  {
    id: 'history-70',
    category: 'history',
    question: 'What was the capital of the Mali Empire?',
    options: ['Timbuktu', 'Gao', 'Djenne', 'Koumbi Saleh'],
    correctAnswer: 'Koumbi Saleh',
    explanation: 'Koumbi Saleh was the capital of the Mali Empire from the 13th to 17th centuries!',
    difficulty: 'hard',
  },
  {
    id: 'history-71',
    category: 'history',
    question: 'Who discovered the principle of electromagnetic induction?',
    options: ['Michael Faraday', 'James Maxwell', 'Thomas Edison', 'Nikola Tesla'],
    correctAnswer: 'Michael Faraday',
    explanation: 'Michael Faraday discovered electromagnetic induction in 1831!',
    difficulty: 'hard',
  },
  {
    id: 'history-72',
    category: 'history',
    question: 'Which battle ended the Byzantine Empire?',
    options: ['Fall of Constantinople', 'Battle of Manzikert', 'Battle of Adrianople', 'Battle of Yarmouk'],
    correctAnswer: 'Fall of Constantinople',
    explanation: 'The Fall of Constantinople to the Ottoman Empire in 1453 marked the end of the Byzantine Empire!',
    difficulty: 'hard',
  },
  {
    id: 'history-73',
    category: 'history',
    question: 'Who was the first person to circumnavigate the globe?',
    options: ['Juan Sebastian Elcano', 'Ferdinand Magellan', 'Francis Drake', 'Vasco da Gama'],
    correctAnswer: 'Juan Sebastian Elcano',
    explanation: 'While Magellan led the expedition, Elcano completed the first circumnavigation after Magellan\'s death!',
    difficulty: 'hard',
  },
  {
    id: 'history-74',
    category: 'history',
    question: 'What was the first writing system ever developed?',
    options: ['Cuneiform', 'Hieroglyphics', 'Oracle Bone Script', 'Linear A'],
    correctAnswer: 'Cuneiform',
    explanation: 'Cuneiform was developed by the Sumerians around 3200 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-75',
    category: 'history',
    question: 'Who invented the first mechanical computer?',
    options: ['Charles Babbage', 'Alan Turing', 'Ada Lovelace', 'John von Neumann'],
    correctAnswer: 'Charles Babbage',
    explanation: 'Charles Babbage designed the Difference Engine in 1822!',
    difficulty: 'hard',
  },
  {
    id: 'history-76',
    category: 'history',
    question: 'Which civilization first developed the concept of democracy?',
    options: ['Ancient Athens', 'Roman Republic', 'Phoenicians', 'Mesopotamians'],
    correctAnswer: 'Ancient Athens',
    explanation: 'Democracy was first developed in Ancient Athens around 500 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-77',
    category: 'history',
    question: 'Who discovered the structure of DNA?',
    options: ['Watson and Crick', 'Rosalind Franklin', 'Linus Pauling', 'Maurice Wilkins'],
    correctAnswer: 'Watson and Crick',
    explanation: 'James Watson and Francis Crick discovered the double helix structure of DNA in 1953!',
    difficulty: 'hard',
  },
  {
    id: 'history-78',
    category: 'history',
    question: 'What was the first civilization to develop a complex system of writing?',
    options: ['Sumerians', 'Egyptians', 'Indus Valley', 'Chinese'],
    correctAnswer: 'Sumerians',
    explanation: 'The Sumerians developed cuneiform writing around 3200 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-79',
    category: 'history',
    question: 'Who was the first scientist to propose the heliocentric model?',
    options: ['Aristarchus', 'Copernicus', 'Galileo', 'Kepler'],
    correctAnswer: 'Aristarchus',
    explanation: 'Aristarchus of Samos proposed a heliocentric model in the 3rd century BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-80',
    category: 'history',
    question: 'What was the first civilization to develop steel-making?',
    options: ['Hittites', 'Indians', 'Chinese', 'Romans'],
    correctAnswer: 'Hittites',
    explanation: 'The Hittites developed steel-making techniques around 1400 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-81',
    category: 'history',
    question: 'Who invented the first practical steam engine?',
    options: ['Thomas Newcomen', 'James Watt', 'George Stephenson', 'Richard Trevithick'],
    correctAnswer: 'Thomas Newcomen',
    explanation: 'Thomas Newcomen invented the first practical steam engine in 1712!',
    difficulty: 'hard',
  },
  {
    id: 'history-82',
    category: 'history',
    question: 'Which ancient civilization first developed the concept of zero?',
    options: ['Ancient Maya', 'Ancient Indians', 'Babylonians', 'Greeks'],
    correctAnswer: 'Ancient Maya',
    explanation: 'The Maya independently developed the concept of zero around 350 CE!',
    difficulty: 'hard',
  },
  {
    id: 'history-83',
    category: 'history',
    question: 'Who was the first person to accurately measure the circumference of Earth?',
    options: ['Eratosthenes', 'Ptolemy', 'Aristotle', 'Archimedes'],
    correctAnswer: 'Eratosthenes',
    explanation: 'Eratosthenes calculated Earth\'s circumference with remarkable accuracy in 240 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-84',
    category: 'history',
    question: 'What was the first civilization to develop a system of law?',
    options: ['Sumerians', 'Babylonians', 'Egyptians', 'Assyrians'],
    correctAnswer: 'Sumerians',
    explanation: 'The Sumerians developed the first written law codes around 2100 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-85',
    category: 'history',
    question: 'Who was the first person to split the atom?',
    options: ['Ernest Rutherford', 'Niels Bohr', 'Marie Curie', 'Albert Einstein'],
    correctAnswer: 'Ernest Rutherford',
    explanation: 'Ernest Rutherford first split the atom in 1917!',
    difficulty: 'hard',
  },
  {
    id: 'history-86',
    category: 'history',
    question: 'What was the first civilization to develop a postal system?',
    options: ['Persians', 'Romans', 'Chinese', 'Egyptians'],
    correctAnswer: 'Persians',
    explanation: 'The Persians developed the first postal system under Cyrus the Great around 550 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-87',
    category: 'history',
    question: 'Who invented the first successful electric light bulb?',
    options: ['Heinrich Göbel', 'Thomas Edison', 'Joseph Swan', 'Alexander Lodygin'],
    correctAnswer: 'Heinrich Göbel',
    explanation: 'Heinrich Göbel invented the first electric light bulb in 1854, predating Edison by 25 years!',
    difficulty: 'hard',
  },
  {
    id: 'history-88',
    category: 'history',
    question: 'Which civilization first developed the concept of infinity?',
    options: ['Ancient Indians', 'Greeks', 'Mayans', 'Chinese'],
    correctAnswer: 'Ancient Indians',
    explanation: 'Ancient Indian mathematicians first developed the concept of infinity around 500 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-89',
    category: 'history',
    question: 'Who was the first person to observe cells under a microscope?',
    options: ['Robert Hooke', 'Antoni van Leeuwenhoek', 'Marcello Malpighi', 'Jan Swammerdam'],
    correctAnswer: 'Robert Hooke',
    explanation: 'Robert Hooke first observed cells in cork under a microscope in 1665!',
    difficulty: 'hard',
  },
  {
    id: 'history-90',
    category: 'history',
    question: 'What was the first civilization to develop a theory of atoms?',
    options: ['Greeks', 'Indians', 'Chinese', 'Persians'],
    correctAnswer: 'Greeks',
    explanation: 'The ancient Greeks, specifically Democritus, developed atomic theory around 400 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-91',
    category: 'history',
    question: 'Who invented the first successful vaccination?',
    options: ['Edward Jenner', 'Louis Pasteur', 'Robert Koch', 'Joseph Lister'],
    correctAnswer: 'Edward Jenner',
    explanation: 'Edward Jenner developed the first vaccine (for smallpox) in 1796!',
    difficulty: 'hard',
  },
  {
    id: 'history-92',
    category: 'history',
    question: 'Which civilization first developed the concept of gravity?',
    options: ['Indians', 'Greeks', 'Chinese', 'Arabs'],
    correctAnswer: 'Indians',
    explanation: 'Ancient Indian astronomer Aryabhata first described the concept of gravity in the 5th century CE!',
    difficulty: 'hard',
  },
  {
    id: 'history-93',
    category: 'history',
    question: 'Who invented the first successful telescope?',
    options: ['Hans Lippershey', 'Galileo Galilei', 'Johannes Kepler', 'Isaac Newton'],
    correctAnswer: 'Hans Lippershey',
    explanation: 'Hans Lippershey invented the first telescope in 1608!',
    difficulty: 'hard',
  },
  {
    id: 'history-94',
    category: 'history',
    question: 'What was the first civilization to develop algebra?',
    options: ['Babylonians', 'Greeks', 'Indians', 'Arabs'],
    correctAnswer: 'Babylonians',
    explanation: 'The Babylonians developed basic algebra around 2000 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-95',
    category: 'history',
    question: 'Who was the first person to map the human genome?',
    options: ['Craig Venter', 'Francis Collins', 'James Watson', 'Frederick Sanger'],
    correctAnswer: 'Craig Venter',
    explanation: 'Craig Venter and his team first mapped the human genome in 2000!',
    difficulty: 'hard',
  },
  {
    id: 'history-96',
    category: 'history',
    question: 'Which civilization first developed the concept of time zones?',
    options: ['British', 'Americans', 'French', 'Germans'],
    correctAnswer: 'British',
    explanation: 'The British developed time zones in the 1840s for their railway system!',
    difficulty: 'hard',
  },
  {
    id: 'history-97',
    category: 'history',
    question: 'Who invented the first successful radio?',
    options: ['Guglielmo Marconi', 'Nikola Tesla', 'Heinrich Hertz', 'James Maxwell'],
    correctAnswer: 'Guglielmo Marconi',
    explanation: 'Guglielmo Marconi invented the first successful radio in 1895!',
    difficulty: 'hard',
  },
  {
    id: 'history-98',
    category: 'history',
    question: 'What was the first civilization to develop trigonometry?',
    options: ['Greeks', 'Indians', 'Egyptians', 'Babylonians'],
    correctAnswer: 'Greeks',
    explanation: 'The ancient Greeks, particularly Hipparchus, developed trigonometry around 150 BCE!',
    difficulty: 'hard',
  },
  {
    id: 'history-99',
    category: 'history',
    question: 'Who invented the first successful typewriter?',
    options: ['Christopher Sholes', 'William Burt', 'James Densmore', 'Carlos Glidden'],
    correctAnswer: 'Christopher Sholes',
    explanation: 'Christopher Sholes invented the first successful typewriter in 1867!',
    difficulty: 'hard',
  },
  {
    id: 'history-100',
    category: 'history',
    question: 'Which civilization first developed the concept of logarithms?',
    options: ['Scottish', 'Indian', 'Persian', 'Chinese'],
    correctAnswer: 'Scottish',
    explanation: 'John Napier, a Scottish mathematician, invented logarithms in 1614!',
    difficulty: 'hard',
  }
]; 