import { Question } from '../types';

export const mathQuestions: Question[] = [
  // Easy Math Questions (34)
  {
    id: 'math-1',
    category: 'math',
    question: 'What is 8 × 7?',
    options: ['54', '56', '58', '60'],
    correctAnswer: '56',
    explanation: '8 × 7 = 56. You can think of it as 8 groups of 7!',
    difficulty: 'easy',
  },
  {
    id: 'math-2',
    category: 'math',
    question: 'What is half of 100?',
    options: ['25', '50', '75', '100'],
    correctAnswer: '50',
    explanation: 'Half means dividing by 2, so 100 ÷ 2 = 50!',
    difficulty: 'easy',
  },
  {
    id: 'math-3',
    category: 'math',
    question: 'How many sides does a hexagon have?',
    options: ['4', '5', '6', '7'],
    correctAnswer: '6',
    explanation: 'A hexagon is a shape with 6 sides and 6 angles!',
    difficulty: 'easy',
  },
  {
    id: 'math-4',
    category: 'math',
    question: 'What is 12 + 15?',
    options: ['25', '27', '29', '31'],
    correctAnswer: '27',
    explanation: 'Adding 12 and 15: first add 10 + 15 = 25, then add 2 more to get 27!',
    difficulty: 'easy',
  },
  {
    id: 'math-5',
    category: 'math',
    question: 'How many minutes are in an hour?',
    options: ['30', '45', '60', '90'],
    correctAnswer: '60',
    explanation: 'There are 60 minutes in one hour!',
    difficulty: 'easy',
  },
  {
    id: 'math-6',
    category: 'math',
    question: 'What is 5 × 6?',
    options: ['25', '30', '35', '40'],
    correctAnswer: '30',
    explanation: '5 × 6 = 30. You can think of it as 5 groups of 6!',
    difficulty: 'easy',
  },
  {
    id: 'math-7',
    category: 'math',
    question: 'What shape has 3 sides?',
    options: ['Square', 'Triangle', 'Circle', 'Rectangle'],
    correctAnswer: 'Triangle',
    explanation: 'A triangle is a shape with exactly 3 sides and 3 angles!',
    difficulty: 'easy',
  },
  {
    id: 'math-8',
    category: 'math',
    question: 'What is 20 - 7?',
    options: ['11', '12', '13', '14'],
    correctAnswer: '13',
    explanation: 'Subtracting 7 from 20: first subtract 7 from 20 to get 13!',
    difficulty: 'easy',
  },
  {
    id: 'math-9',
    category: 'math',
    question: 'How many sides does a square have?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: 'A square has 4 equal sides and 4 right angles!',
    difficulty: 'easy',
  },
  {
    id: 'math-10',
    category: 'math',
    question: 'What is 4 × 9?',
    options: ['32', '34', '36', '38'],
    correctAnswer: '36',
    explanation: '4 × 9 = 36. You can think of it as 4 groups of 9!',
    difficulty: 'easy',
  },
  {
    id: 'math-11',
    category: 'math',
    question: 'What number comes after 99?',
    options: ['98', '99', '100', '101'],
    correctAnswer: '100',
    explanation: 'After 99 comes 100, which is the first three-digit number!',
    difficulty: 'easy',
  },
  {
    id: 'math-12',
    category: 'math',
    question: 'What is 25 + 8?',
    options: ['31', '32', '33', '34'],
    correctAnswer: '33',
    explanation: 'Adding 25 and 8: first add 25 + 5 = 30, then add 3 more to get 33!',
    difficulty: 'easy',
  },
  {
    id: 'math-13',
    category: 'math',
    question: 'How many hours are in a day?',
    options: ['12', '18', '24', '36'],
    correctAnswer: '24',
    explanation: 'There are 24 hours in one day!',
    difficulty: 'easy',
  },
  {
    id: 'math-14',
    category: 'math',
    question: 'What is double 15?',
    options: ['25', '30', '35', '40'],
    correctAnswer: '30',
    explanation: 'Double means multiply by 2, so 15 × 2 = 30!',
    difficulty: 'easy',
  },
  {
    id: 'math-15',
    category: 'math',
    question: 'What is 100 - 25?',
    options: ['65', '70', '75', '80'],
    correctAnswer: '75',
    explanation: 'Subtracting 25 from 100: first subtract 20 to get 80, then subtract 5 to get 75!',
    difficulty: 'easy',
  },
  {
    id: 'math-16',
    category: 'math',
    question: 'How many corners does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'A triangle has 3 corners (vertices) where its sides meet!',
    difficulty: 'easy',
  },
  {
    id: 'math-17',
    category: 'math',
    question: 'What is 3 × 8?',
    options: ['21', '22', '23', '24'],
    correctAnswer: '24',
    explanation: '3 × 8 = 24. You can think of it as 3 groups of 8!',
    difficulty: 'easy',
  },
  {
    id: 'math-18',
    category: 'math',
    question: 'What is 40 + 35?',
    options: ['70', '75', '80', '85'],
    correctAnswer: '75',
    explanation: 'Adding 40 and 35: first add 40 + 30 = 70, then add 5 more to get 75!',
    difficulty: 'easy',
  },
  {
    id: 'math-19',
    category: 'math',
    question: 'How many days are in a week?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
    explanation: 'There are 7 days in a week: Monday through Sunday!',
    difficulty: 'easy',
  },
  {
    id: 'math-20',
    category: 'math',
    question: 'What is 6 × 4?',
    options: ['20', '22', '24', '26'],
    correctAnswer: '24',
    explanation: '6 × 4 = 24. You can think of it as 6 groups of 4!',
    difficulty: 'easy',
  },
  {
    id: 'math-21',
    category: 'math',
    question: 'What number is ten less than 50?',
    options: ['30', '35', '40', '45'],
    correctAnswer: '40',
    explanation: 'To find ten less than 50, subtract 10 from 50: 50 - 10 = 40!',
    difficulty: 'easy',
  },
  {
    id: 'math-22',
    category: 'math',
    question: 'How many sides does a pentagon have?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'A pentagon is a shape with 5 sides and 5 angles!',
    difficulty: 'easy',
  },
  {
    id: 'math-23',
    category: 'math',
    question: 'What is 16 + 9?',
    options: ['23', '24', '25', '26'],
    correctAnswer: '25',
    explanation: 'Adding 16 and 9: first add 16 + 4 = 20, then add 5 more to get 25!',
    difficulty: 'easy',
  },
  {
    id: 'math-24',
    category: 'math',
    question: 'What is half of 50?',
    options: ['20', '25', '30', '35'],
    correctAnswer: '25',
    explanation: 'Half means dividing by 2, so 50 ÷ 2 = 25!',
    difficulty: 'easy',
  },
  {
    id: 'math-25',
    category: 'math',
    question: 'What is 7 × 5?',
    options: ['30', '35', '40', '45'],
    correctAnswer: '35',
    explanation: '7 × 5 = 35. You can think of it as 7 groups of 5!',
    difficulty: 'easy',
  },
  {
    id: 'math-26',
    category: 'math',
    question: 'What is 30 - 12?',
    options: ['16', '17', '18', '19'],
    correctAnswer: '18',
    explanation: 'Subtracting 12 from 30: first subtract 10 to get 20, then subtract 2 to get 18!',
    difficulty: 'easy',
  },
  {
    id: 'math-27',
    category: 'math',
    question: 'How many months are in a year?',
    options: ['10', '11', '12', '13'],
    correctAnswer: '12',
    explanation: 'There are 12 months in one year!',
    difficulty: 'easy',
  },
  {
    id: 'math-28',
    category: 'math',
    question: 'What is 9 × 3?',
    options: ['24', '25', '26', '27'],
    correctAnswer: '27',
    explanation: '9 × 3 = 27. You can think of it as 9 groups of 3!',
    difficulty: 'easy',
  },
  {
    id: 'math-29',
    category: 'math',
    question: 'What is 45 + 10?',
    options: ['50', '55', '60', '65'],
    correctAnswer: '55',
    explanation: 'Adding 10 to 45 gives you 55!',
    difficulty: 'easy',
  },
  {
    id: 'math-30',
    category: 'math',
    question: 'What shape is a circle?',
    options: ['Round', 'Square', 'Triangle', 'Rectangle'],
    correctAnswer: 'Round',
    explanation: 'A circle is a round shape with no corners!',
    difficulty: 'easy',
  },
  {
    id: 'math-31',
    category: 'math',
    question: 'What is 60 - 15?',
    options: ['35', '40', '45', '50'],
    correctAnswer: '45',
    explanation: 'Subtracting 15 from 60: first subtract 10 to get 50, then subtract 5 to get 45!',
    difficulty: 'easy',
  },
  {
    id: 'math-32',
    category: 'math',
    question: 'What is double 20?',
    options: ['30', '35', '40', '45'],
    correctAnswer: '40',
    explanation: 'Double means multiply by 2, so 20 × 2 = 40!',
    difficulty: 'easy',
  },
  {
    id: 'math-33',
    category: 'math',
    question: 'How many tens are in 100?',
    options: ['5', '10', '15', '20'],
    correctAnswer: '10',
    explanation: '100 can be divided into 10 groups of 10!',
    difficulty: 'easy',
  },
  {
    id: 'math-34',
    category: 'math',
    question: 'What is 8 × 4?',
    options: ['28', '30', '32', '34'],
    correctAnswer: '32',
    explanation: '8 × 4 = 32. You can think of it as 8 groups of 4!',
    difficulty: 'easy',
  },
  // Medium Math Questions (33)
  {
    id: 'math-35',
    category: 'math',
    question: 'What is the area of a square with sides of 7 units?',
    options: ['49', '14', '28', '21'],
    correctAnswer: '49',
    explanation: 'The area of a square is side × side, so 7 × 7 = 49 square units!',
    difficulty: 'medium',
  },
  {
    id: 'math-36',
    category: 'math',
    question: 'What is 15 × 6?',
    options: ['80', '85', '90', '95'],
    correctAnswer: '90',
    explanation: '15 × 6 = 90. You can break it down: (10 × 6) + (5 × 6) = 60 + 30 = 90!',
    difficulty: 'medium',
  },
  {
    id: 'math-37',
    category: 'math',
    question: 'How many degrees are in a right angle?',
    options: ['45', '60', '90', '180'],
    correctAnswer: '90',
    explanation: 'A right angle is exactly 90 degrees!',
    difficulty: 'medium',
  },
  {
    id: 'math-38',
    category: 'math',
    question: 'What is 144 ÷ 12?',
    options: ['10', '12', '14', '16'],
    correctAnswer: '12',
    explanation: '144 ÷ 12 = 12 because 12 × 12 = 144!',
    difficulty: 'medium',
  },
  {
    id: 'math-39',
    category: 'math',
    question: 'What is the perimeter of a square with sides of 8 units?',
    options: ['24', '28', '32', '36'],
    correctAnswer: '32',
    explanation: 'The perimeter is the sum of all sides: 8 + 8 + 8 + 8 = 32 units!',
    difficulty: 'medium',
  },
  {
    id: 'math-40',
    category: 'math',
    question: 'What is 125 - 48?',
    options: ['67', '77', '87', '97'],
    correctAnswer: '77',
    explanation: 'Subtract 48 from 125: first subtract 40 to get 85, then subtract 8 to get 77!',
    difficulty: 'medium',
  },
  {
    id: 'math-41',
    category: 'math',
    question: 'How many faces does a cube have?',
    options: ['4', '6', '8', '12'],
    correctAnswer: '6',
    explanation: 'A cube has 6 square faces!',
    difficulty: 'medium',
  },
  {
    id: 'math-42',
    category: 'math',
    question: 'What is 1/4 of 100?',
    options: ['15', '20', '25', '30'],
    correctAnswer: '25',
    explanation: 'To find 1/4 of 100, divide 100 by 4: 100 ÷ 4 = 25!',
    difficulty: 'medium',
  },
  {
    id: 'math-43',
    category: 'math',
    question: 'What is 13 × 7?',
    options: ['81', '87', '91', '97'],
    correctAnswer: '91',
    explanation: '13 × 7 = 91. You can break it down: (10 × 7) + (3 × 7) = 70 + 21 = 91!',
    difficulty: 'medium',
  },
  {
    id: 'math-44',
    category: 'math',
    question: 'How many degrees are in a triangle?',
    options: ['90', '120', '180', '360'],
    correctAnswer: '180',
    explanation: 'The angles in a triangle always add up to 180 degrees!',
    difficulty: 'medium',
  },
  {
    id: 'math-45',
    category: 'math',
    question: 'What is 256 ÷ 8?',
    options: ['28', '30', '32', '34'],
    correctAnswer: '32',
    explanation: '256 ÷ 8 = 32 because 8 × 32 = 256!',
    difficulty: 'medium',
  },
  {
    id: 'math-46',
    category: 'math',
    question: 'What is the area of a rectangle with length 9 and width 5?',
    options: ['35', '40', '45', '50'],
    correctAnswer: '45',
    explanation: 'The area of a rectangle is length × width, so 9 × 5 = 45 square units!',
    difficulty: 'medium',
  },
  {
    id: 'math-47',
    category: 'math',
    question: 'What is 3/4 of 80?',
    options: ['50', '55', '60', '65'],
    correctAnswer: '60',
    explanation: 'To find 3/4 of 80: first find 1/4 (80 ÷ 4 = 20), then multiply by 3: 20 × 3 = 60!',
    difficulty: 'medium',
  },
  {
    id: 'math-48',
    category: 'math',
    question: 'What is 17 × 6?',
    options: ['92', '97', '102', '107'],
    correctAnswer: '102',
    explanation: '17 × 6 = 102. You can break it down: (10 × 6) + (7 × 6) = 60 + 42 = 102!',
    difficulty: 'medium',
  },
  {
    id: 'math-49',
    category: 'math',
    question: 'How many edges does a cube have?',
    options: ['8', '10', '12', '14'],
    correctAnswer: '12',
    explanation: 'A cube has 12 edges where its faces meet!',
    difficulty: 'medium',
  },
  {
    id: 'math-50',
    category: 'math',
    question: 'What is 185 - 97?',
    options: ['67', '77', '87', '97'],
    correctAnswer: '88',
    explanation: 'Subtract 97 from 185: first subtract 100 to get 85, then add 3 to get 88!',
    difficulty: 'medium',
  },
  {
    id: 'math-51',
    category: 'math',
    question: 'What is 2/5 of 100?',
    options: ['30', '35', '40', '45'],
    correctAnswer: '40',
    explanation: 'To find 2/5 of 100: first find 1/5 (100 ÷ 5 = 20), then multiply by 2: 20 × 2 = 40!',
    difficulty: 'medium',
  },
  {
    id: 'math-52',
    category: 'math',
    question: 'What is 16 × 7?',
    options: ['102', '107', '112', '117'],
    correctAnswer: '112',
    explanation: '16 × 7 = 112. You can break it down: (10 × 7) + (6 × 7) = 70 + 42 = 112!',
    difficulty: 'medium',
  },
  {
    id: 'math-53',
    category: 'math',
    question: 'How many degrees are in a circle?',
    options: ['180', '270', '360', '400'],
    correctAnswer: '360',
    explanation: 'A circle contains 360 degrees!',
    difficulty: 'medium',
  },
  {
    id: 'math-54',
    category: 'math',
    question: 'What is 225 ÷ 15?',
    options: ['10', '15', '20', '25'],
    correctAnswer: '15',
    explanation: '225 ÷ 15 = 15 because 15 × 15 = 225!',
    difficulty: 'medium',
  },
  {
    id: 'math-55',
    category: 'math',
    question: 'What is the perimeter of a rectangle with length 12 and width 7?',
    options: ['34', '38', '42', '46'],
    correctAnswer: '38',
    explanation: 'The perimeter is 2 × (length + width), so 2 × (12 + 7) = 2 × 19 = 38 units!',
    difficulty: 'medium',
  },
  {
    id: 'math-56',
    category: 'math',
    question: 'What is 5/8 of 40?',
    options: ['20', '25', '30', '35'],
    correctAnswer: '25',
    explanation: 'To find 5/8 of 40: first find 1/8 (40 ÷ 8 = 5), then multiply by 5: 5 × 5 = 25!',
    difficulty: 'medium',
  },
  {
    id: 'math-57',
    category: 'math',
    question: 'What is 14 × 8?',
    options: ['102', '112', '122', '132'],
    correctAnswer: '112',
    explanation: '14 × 8 = 112. You can break it down: (10 × 8) + (4 × 8) = 80 + 32 = 112!',
    difficulty: 'medium',
  },
  {
    id: 'math-58',
    category: 'math',
    question: 'How many vertices (corners) does a cube have?',
    options: ['4', '6', '8', '12'],
    correctAnswer: '8',
    explanation: 'A cube has 8 vertices where three edges meet!',
    difficulty: 'medium',
  },
  {
    id: 'math-59',
    category: 'math',
    question: 'What is 245 - 168?',
    options: ['67', '77', '87', '97'],
    correctAnswer: '77',
    explanation: 'Subtract 168 from 245: first subtract 160 to get 85, then subtract 8 to get 77!',
    difficulty: 'medium',
  },
  {
    id: 'math-60',
    category: 'math',
    question: 'What is 3/5 of 150?',
    options: ['80', '85', '90', '95'],
    correctAnswer: '90',
    explanation: 'To find 3/5 of 150: first find 1/5 (150 ÷ 5 = 30), then multiply by 3: 30 × 3 = 90!',
    difficulty: 'medium',
  },
  {
    id: 'math-61',
    category: 'math',
    question: 'What is 18 × 6?',
    options: ['98', '103', '108', '113'],
    correctAnswer: '108',
    explanation: '18 × 6 = 108. You can break it down: (10 × 6) + (8 × 6) = 60 + 48 = 108!',
    difficulty: 'medium',
  },
  {
    id: 'math-62',
    category: 'math',
    question: 'What is the area of a triangle with base 8 and height 6?',
    options: ['20', '24', '28', '32'],
    correctAnswer: '24',
    explanation: 'The area of a triangle is (base × height) ÷ 2, so (8 × 6) ÷ 2 = 48 ÷ 2 = 24 square units!',
    difficulty: 'medium',
  },
  {
    id: 'math-63',
    category: 'math',
    question: 'What is 196 ÷ 14?',
    options: ['11', '12', '13', '14'],
    correctAnswer: '14',
    explanation: '196 ÷ 14 = 14 because 14 × 14 = 196!',
    difficulty: 'medium',
  },
  {
    id: 'math-64',
    category: 'math',
    question: 'What is 2/3 of 90?',
    options: ['50', '55', '60', '65'],
    correctAnswer: '60',
    explanation: 'To find 2/3 of 90: first find 1/3 (90 ÷ 3 = 30), then multiply by 2: 30 × 2 = 60!',
    difficulty: 'medium',
  },
  {
    id: 'math-65',
    category: 'math',
    question: 'What is 19 × 5?',
    options: ['85', '90', '95', '100'],
    correctAnswer: '95',
    explanation: '19 × 5 = 95. You can break it down: (10 × 5) + (9 × 5) = 50 + 45 = 95!',
    difficulty: 'medium',
  },
  {
    id: 'math-66',
    category: 'math',
    question: 'How many faces does a triangular prism have?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'A triangular prism has 5 faces: 2 triangular faces and 3 rectangular faces!',
    difficulty: 'medium',
  },
  {
    id: 'math-67',
    category: 'math',
    question: 'What is 156 - 89?',
    options: ['57', '67', '77', '87'],
    correctAnswer: '67',
    explanation: 'Subtract 89 from 156: first subtract 80 to get 76, then subtract 9 to get 67!',
    difficulty: 'medium',
  },
  // Hard Math Questions (33)
  {
    id: 'math-68',
    category: 'math',
    question: 'If 3x + 7 = 22, what is x?',
    options: ['5', '6', '4', '7'],
    correctAnswer: '5',
    explanation: 'Subtract 7 from both sides: 3x = 15, then divide by 3: x = 5!',
    difficulty: 'hard',
  },
  {
    id: 'math-69',
    category: 'math',
    question: 'What is the square root of 144?',
    options: ['10', '11', '12', '13'],
    correctAnswer: '12',
    explanation: '12 × 12 = 144, so the square root of 144 is 12!',
    difficulty: 'hard',
  },
  {
    id: 'math-70',
    category: 'math',
    question: 'What is 25% of 360?',
    options: ['80', '90', '100', '110'],
    correctAnswer: '90',
    explanation: '25% is the same as 1/4, so 360 ÷ 4 = 90!',
    difficulty: 'hard',
  },
  {
    id: 'math-71',
    category: 'math',
    question: 'What is the area of a circle with radius 5 units? (Use π = 3.14)',
    options: ['75.5', '78.5', '81.5', '84.5'],
    correctAnswer: '78.5',
    explanation: 'The area of a circle is πr², so 3.14 × 5² = 3.14 × 25 = 78.5 square units!',
    difficulty: 'hard',
  },
  {
    id: 'math-72',
    category: 'math',
    question: 'What is 15% of 200?',
    options: ['25', '30', '35', '40'],
    correctAnswer: '30',
    explanation: 'To find 15% of 200: (15/100) × 200 = 30!',
    difficulty: 'hard',
  },
  {
    id: 'math-73',
    category: 'math',
    question: 'If y = 2x + 3 and x = 4, what is y?',
    options: ['8', '9', '10', '11'],
    correctAnswer: '11',
    explanation: 'Replace x with 4: y = 2(4) + 3 = 8 + 3 = 11!',
    difficulty: 'hard',
  },
  {
    id: 'math-74',
    category: 'math',
    question: 'What is the volume of a cube with sides of 4 units?',
    options: ['48', '56', '64', '72'],
    correctAnswer: '64',
    explanation: 'The volume of a cube is side³, so 4 × 4 × 4 = 64 cubic units!',
    difficulty: 'hard',
  },
  {
    id: 'math-75',
    category: 'math',
    question: 'What is 2³ × 2⁴?',
    options: ['64', '96', '128', '256'],
    correctAnswer: '128',
    explanation: '2³ × 2⁴ = 2⁷ = 128 (add the exponents: 3 + 4 = 7)!',
    difficulty: 'hard',
  },
  {
    id: 'math-76',
    category: 'math',
    question: 'What is the perimeter of a regular octagon with sides of 5 units?',
    options: ['35', '40', '45', '50'],
    correctAnswer: '40',
    explanation: 'An octagon has 8 sides, so the perimeter is 8 × 5 = 40 units!',
    difficulty: 'hard',
  },
  {
    id: 'math-77',
    category: 'math',
    question: 'If 4(x - 2) = 24, what is x?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: 'First divide by 4: x - 2 = 6, then add 2: x = 8!',
    difficulty: 'hard',
  },
  {
    id: 'math-78',
    category: 'math',
    question: 'What is 75% of 240?',
    options: ['160', '170', '180', '190'],
    correctAnswer: '180',
    explanation: '75% is the same as 3/4, so (240 × 3) ÷ 4 = 180!',
    difficulty: 'hard',
  },
  {
    id: 'math-79',
    category: 'math',
    question: 'What is the circumference of a circle with diameter 10 units? (Use π = 3.14)',
    options: ['28.4', '31.4', '34.4', '37.4'],
    correctAnswer: '31.4',
    explanation: 'The circumference is π × diameter, so 3.14 × 10 = 31.4 units!',
    difficulty: 'hard',
  },
  {
    id: 'math-80',
    category: 'math',
    question: 'What is 35% of 400?',
    options: ['120', '130', '140', '150'],
    correctAnswer: '140',
    explanation: 'To find 35% of 400: (35/100) × 400 = 140!',
    difficulty: 'hard',
  },
  {
    id: 'math-81',
    category: 'math',
    question: 'If 2y - 5 = 11, what is y?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
    explanation: 'Add 5 to both sides: 2y = 16, then divide by 2: y = 8!',
    difficulty: 'hard',
  },
  {
    id: 'math-82',
    category: 'math',
    question: 'What is the volume of a rectangular prism with length 6, width 4, and height 3 units?',
    options: ['62', '68', '72', '78'],
    correctAnswer: '72',
    explanation: 'The volume is length × width × height, so 6 × 4 × 3 = 72 cubic units!',
    difficulty: 'hard',
  },
  {
    id: 'math-83',
    category: 'math',
    question: 'What is 5² × 5³?',
    options: ['125', '625', '3125', '15625'],
    correctAnswer: '3125',
    explanation: '5² × 5³ = 5⁵ = 3125 (add the exponents: 2 + 3 = 5)!',
    difficulty: 'hard',
  },
  {
    id: 'math-84',
    category: 'math',
    question: 'What is the area of a trapezoid with parallel sides of 8 and 12 units and height 5 units?',
    options: ['45', '50', '55', '60'],
    correctAnswer: '50',
    explanation: 'The area is [(a + b) × h] ÷ 2, where a and b are parallel sides and h is height. So [(8 + 12) × 5] ÷ 2 = 50 square units!',
    difficulty: 'hard',
  },
  {
    id: 'math-85',
    category: 'math',
    question: 'What is the sum of angles in a pentagon?',
    options: ['360°', '450°', '540°', '720°'],
    correctAnswer: '540°',
    explanation: 'In a pentagon, the sum of interior angles is (5-2) × 180° = 3 × 180° = 540°!',
    difficulty: 'hard',
  },
  {
    id: 'math-86',
    category: 'math',
    question: 'If 5y + 10 = 35, what is y?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'Subtract 10 from both sides: 5y = 25, then divide by 5: y = 5!',
    difficulty: 'hard',
  },
  {
    id: 'math-87',
    category: 'math',
    question: 'What is 45% of 300?',
    options: ['125', '135', '145', '155'],
    correctAnswer: '135',
    explanation: 'To find 45% of 300: (45/100) × 300 = 135!',
    difficulty: 'hard',
  },
  {
    id: 'math-88',
    category: 'math',
    question: 'What is the volume of a sphere with radius 3 units? (Use π = 3.14)',
    options: ['113', '113.04', '113.08', '113.12'],
    correctAnswer: '113.04',
    explanation: 'The volume of a sphere is (4/3)πr³, so (4/3) × 3.14 × 27 = 113.04 cubic units!',
    difficulty: 'hard',
  },
  {
    id: 'math-89',
    category: 'math',
    question: 'What is 3⁴?',
    options: ['71', '81', '91', '101'],
    correctAnswer: '81',
    explanation: '3⁴ means 3 × 3 × 3 × 3 = 81!',
    difficulty: 'hard',
  },
  {
    id: 'math-90',
    category: 'math',
    question: 'What is the area of a regular hexagon with side length 4 units? (Use √3 = 1.73)',
    options: ['41.52', '41.56', '41.58', '41.62'],
    correctAnswer: '41.56',
    explanation: 'The area of a regular hexagon is (3√3/2) × s², where s is the side length. So (3 × 1.73 × 16) ÷ 2 = 41.56 square units!',
    difficulty: 'hard',
  },
  {
    id: 'math-91',
    category: 'math',
    question: 'If 8(x + 3) = 56, what is x?',
    options: ['3', '4', '5', '6'],
    correctAnswer: '4',
    explanation: 'First divide by 8: x + 3 = 7, then subtract 3: x = 4!',
    difficulty: 'hard',
  },
  {
    id: 'math-92',
    category: 'math',
    question: 'What is 85% of 160?',
    options: ['126', '136', '146', '156'],
    correctAnswer: '136',
    explanation: 'To find 85% of 160: (85/100) × 160 = 136!',
    difficulty: 'hard',
  },
  {
    id: 'math-93',
    category: 'math',
    question: 'What is the surface area of a cube with sides of 5 units?',
    options: ['120', '130', '140', '150'],
    correctAnswer: '150',
    explanation: 'The surface area of a cube is 6s², where s is the side length. So 6 × 5² = 6 × 25 = 150 square units!',
    difficulty: 'hard',
  },
  {
    id: 'math-94',
    category: 'math',
    question: 'What is 4³ × 4²?',
    options: ['1024', '1124', '1224', '1324'],
    correctAnswer: '1024',
    explanation: '4³ × 4² = 4⁵ = 1024 (add the exponents: 3 + 2 = 5)!',
    difficulty: 'hard',
  },
  {
    id: 'math-95',
    category: 'math',
    question: 'What is the perimeter of a regular pentagon with sides of 7 units?',
    options: ['25', '30', '35', '40'],
    correctAnswer: '35',
    explanation: 'A pentagon has 5 sides, so the perimeter is 5 × 7 = 35 units!',
    difficulty: 'hard',
  },
  {
    id: 'math-96',
    category: 'math',
    question: 'If 3(y - 4) = 21, what is y?',
    options: ['9', '10', '11', '12'],
    correctAnswer: '11',
    explanation: 'First divide by 3: y - 4 = 7, then add 4: y = 11!',
    difficulty: 'hard',
  },
  {
    id: 'math-97',
    category: 'math',
    question: 'What is 65% of 240?',
    options: ['146', '156', '166', '176'],
    correctAnswer: '156',
    explanation: 'To find 65% of 240: (65/100) × 240 = 156!',
    difficulty: 'hard',
  },
  {
    id: 'math-98',
    category: 'math',
    question: 'What is the volume of a cylinder with radius 4 units and height 6 units? (Use π = 3.14)',
    options: ['301.44', '301.54', '301.64', '301.74'],
    correctAnswer: '301.44',
    explanation: 'The volume of a cylinder is πr²h, so 3.14 × 16 × 6 = 301.44 cubic units!',
    difficulty: 'hard',
  },
  {
    id: 'math-99',
    category: 'math',
    question: 'What is 6² × 6³?',
    options: ['46656', '46666', '46676', '46686'],
    correctAnswer: '46656',
    explanation: '6² × 6³ = 6⁵ = 46656 (add the exponents: 2 + 3 = 5)!',
    difficulty: 'hard',
  },
  {
    id: 'math-100',
    category: 'math',
    question: 'What is the area of a rhombus with diagonals of 8 and 12 units?',
    options: ['38', '48', '58', '68'],
    correctAnswer: '48',
    explanation: 'The area of a rhombus is (d₁ × d₂) ÷ 2, where d₁ and d₂ are the diagonals. So (8 × 12) ÷ 2 = 48 square units!',
    difficulty: 'hard',
  }
]; 