import { Question } from '../types';

export const scienceQuestions: Question[] = [
  // Easy Science Questions (34)
  {
    id: 'science-1',
    category: 'science',
    question: 'What is the closest star to Earth?',
    options: ['Sun', 'Moon', 'Mars', 'Venus'],
    correctAnswer: 'Sun',
    explanation: 'The Sun is our closest star, providing light and heat to Earth!',
    funFact: 'The Sun is so large that about 1.3 million Earths could fit inside it!',
    difficulty: 'easy',
  },
  {
    id: 'science-2',
    category: 'science',
    question: 'Which planet is known as the Red Planet?',
    options: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
    correctAnswer: 'Mars',
    explanation: 'Mars appears red because of iron oxide (rust) on its surface!',
    funFact: 'Mars has the largest volcano in our solar system, Olympus Mons, which is about 3 times taller than Mount Everest!',
    difficulty: 'easy',
  },
  {
    id: 'science-3',
    category: 'science',
    question: 'What is the hardest natural substance?',
    options: ['Diamond', 'Gold', 'Iron', 'Platinum'],
    correctAnswer: 'Diamond',
    explanation: 'Diamond is the hardest natural material known to humans!',
    funFact: 'Diamonds are actually made of pure carbon, just like the graphite in pencils, but arranged in a different crystal structure!',
    difficulty: 'easy',
  },
  {
    id: 'science-4',
    category: 'science',
    question: 'Which animal has the longest neck?',
    options: ['Giraffe', 'Elephant', 'Camel', 'Zebra'],
    correctAnswer: 'Giraffe',
    explanation: 'Giraffes have the longest necks of any animal, helping them reach leaves high in trees!',
    funFact: 'Despite their long necks, giraffes have the same number of neck vertebrae (7) as humans do!',
    difficulty: 'easy',
  },
  {
    id: 'science-5',
    category: 'science',
    question: 'What is the fastest land animal?',
    options: ['Cheetah', 'Lion', 'Tiger', 'Leopard'],
    correctAnswer: 'Cheetah',
    explanation: 'Cheetahs can run up to 70 miles per hour in short bursts!',
    funFact: 'Cheetahs can accelerate from 0 to 60 miles per hour in just 3 seconds, faster than most sports cars!',
    difficulty: 'easy',
  },
  {
    id: 'science-6',
    category: 'science',
    question: 'Which is the largest organ in the human body?',
    options: ['Skin', 'Heart', 'Brain', 'Liver'],
    correctAnswer: 'Skin',
    explanation: 'The skin is the largest organ, covering and protecting our entire body!',
    funFact: 'The average adult\'s skin weighs about 8 pounds and covers an area of about 22 square feet!',
    difficulty: 'easy',
  },
  {
    id: 'science-7',
    category: 'science',
    question: 'What is the main gas that plants need to grow?',
    options: ['Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 'Carbon Dioxide',
    explanation: 'Plants use carbon dioxide from the air to make their food through photosynthesis!',
    funFact: 'Plants actually produce oxygen as a waste product during photosynthesis, which is why they are so important for our atmosphere!',
    difficulty: 'easy',
  },
  {
    id: 'science-8',
    category: 'science',
    question: 'Which planet has the most visible rings?',
    options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
    correctAnswer: 'Saturn',
    explanation: 'Saturn has the most visible and spectacular ring system in our solar system!',
    funFact: 'Saturn\'s rings are made mostly of ice and rock particles, ranging in size from tiny grains to boulders as large as houses!',
    difficulty: 'easy',
  },
  {
    id: 'science-9',
    category: 'science',
    question: 'What is the smallest unit of matter?',
    options: ['Atom', 'Cell', 'Molecule', 'Electron'],
    correctAnswer: 'Atom',
    explanation: 'Atoms are the smallest units of matter that retain the properties of an element!',
    funFact: 'Atoms are mostly empty space - if an atom was the size of a football stadium, the nucleus would be about the size of a pea!',
    difficulty: 'easy',
  },
  {
    id: 'science-10',
    category: 'science',
    question: 'Which animal has the largest brain?',
    options: ['Sperm Whale', 'Elephant', 'Dolphin', 'Gorilla'],
    correctAnswer: 'Sperm Whale',
    explanation: 'The sperm whale has the largest brain of any animal on Earth!',
    funFact: 'A sperm whale\'s brain can weigh up to 20 pounds, which is about 6 times larger than a human brain!',
    difficulty: 'easy',
  },
  {
    id: 'science-11',
    category: 'science',
    question: 'Which animal can live both in water and on land?',
    options: ['Frog', 'Fish', 'Bird', 'Lion'],
    correctAnswer: 'Frog',
    explanation: 'Frogs are amphibians, which means they can live both in water and on land!',
    difficulty: 'easy',
  },
  {
    id: 'science-12',
    category: 'science',
    question: 'What do bees collect from flowers?',
    options: ['Nectar', 'Water', 'Leaves', 'Seeds'],
    correctAnswer: 'Nectar',
    explanation: 'Bees collect nectar from flowers to make honey!',
    difficulty: 'easy',
  },
  {
    id: 'science-13',
    category: 'science',
    question: 'Which planet is closest to the Sun?',
    options: ['Mercury', 'Venus', 'Earth', 'Mars'],
    correctAnswer: 'Mercury',
    explanation: 'Mercury is the closest planet to the Sun and also the smallest planet!',
    difficulty: 'easy',
  },
  {
    id: 'science-14',
    category: 'science',
    question: 'What is the main gas in the air we breathe?',
    options: ['Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Hydrogen'],
    correctAnswer: 'Nitrogen',
    explanation: 'The air we breathe is about 78% nitrogen, while oxygen makes up about 21%!',
    difficulty: 'easy',
  },
  {
    id: 'science-15',
    category: 'science',
    question: 'What do plants need to make their own food?',
    options: ['Sunlight', 'Meat', 'Milk', 'Sugar'],
    correctAnswer: 'Sunlight',
    explanation: 'Plants use sunlight to make their own food through photosynthesis!',
    difficulty: 'easy',
  },
  {
    id: 'science-16',
    category: 'science',
    question: 'Which sense organ helps us keep our balance?',
    options: ['Ears', 'Eyes', 'Nose', 'Tongue'],
    correctAnswer: 'Ears',
    explanation: 'The inner ear contains fluid that helps us maintain our balance!',
    difficulty: 'easy',
  },
  {
    id: 'science-17',
    category: 'science',
    question: 'What is the natural satellite of Earth?',
    options: ['Moon', 'Sun', 'Mars', 'Venus'],
    correctAnswer: 'Moon',
    explanation: 'The Moon is Earth\'s only natural satellite and orbits around our planet!',
    difficulty: 'easy',
  },
  {
    id: 'science-18',
    category: 'science',
    question: 'Which animal never sleeps?',
    options: ['Bullfrog', 'Cat', 'Dog', 'Horse'],
    correctAnswer: 'Bullfrog',
    explanation: 'Bullfrogs don\'t sleep - they rest with their eyes open!',
    difficulty: 'easy',
  },
  {
    id: 'science-19',
    category: 'science',
    question: 'What is the largest mammal in the world?',
    options: ['Blue Whale', 'Elephant', 'Giraffe', 'Hippopotamus'],
    correctAnswer: 'Blue Whale',
    explanation: 'The Blue Whale is the largest animal that has ever lived on Earth!',
    difficulty: 'easy',
  },
  {
    id: 'science-20',
    category: 'science',
    question: 'Which vitamin does your body produce when you are in the sun?',
    options: ['Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B'],
    correctAnswer: 'Vitamin D',
    explanation: 'Your skin produces Vitamin D when exposed to sunlight!',
    difficulty: 'easy',
  },
  {
    id: 'science-21',
    category: 'science',
    question: 'What is the hardest bone in the human body?',
    options: ['Jawbone', 'Skull', 'Femur', 'Spine'],
    correctAnswer: 'Jawbone',
    explanation: 'The jawbone is the hardest bone in the human body!',
    difficulty: 'easy',
  },
  {
    id: 'science-22',
    category: 'science',
    question: 'What is the study of weather called?',
    options: ['Meteorology', 'Biology', 'Geology', 'Astronomy'],
    correctAnswer: 'Meteorology',
    explanation: 'Meteorology is the science that deals with weather and weather forecasting!',
    difficulty: 'easy',
  },
  {
    id: 'science-23',
    category: 'science',
    question: 'What is the smallest bone in the human body?',
    options: ['Stapes', 'Femur', 'Radius', 'Tibia'],
    correctAnswer: 'Stapes',
    explanation: 'The stapes is a tiny bone in your ear that helps you hear!',
    difficulty: 'easy',
  },
  {
    id: 'science-24',
    category: 'science',
    question: 'Which part of the plant makes food?',
    options: ['Leaves', 'Roots', 'Stem', 'Flower'],
    correctAnswer: 'Leaves',
    explanation: 'Leaves make food for the plant through photosynthesis!',
    difficulty: 'easy',
  },
  {
    id: 'science-25',
    category: 'science',
    question: 'What is the largest planet in our solar system?',
    options: ['Jupiter', 'Saturn', 'Mars', 'Earth'],
    correctAnswer: 'Jupiter',
    explanation: 'Jupiter is so big that more than 1,300 Earths could fit inside it!',
    funFact: 'Jupiter has a Great Red Spot that is actually a giant storm that has been raging for at least 400 years!',
    difficulty: 'easy',
  },
  {
    id: 'science-26',
    category: 'science',
    question: 'Which animal can change its color to match its surroundings?',
    options: ['Chameleon', 'Snake', 'Lizard', 'Turtle'],
    correctAnswer: 'Chameleon',
    explanation: 'Chameleons can change their color to hide from predators or communicate!',
    funFact: 'Chameleons don\'t just change color to camouflage - they also change color based on their mood, temperature, and to communicate with other chameleons!',
    difficulty: 'easy',
  },
  {
    id: 'science-27',
    category: 'science',
    question: 'What do you call a group of stars that forms a pattern?',
    options: ['Constellation', 'Galaxy', 'Solar System', 'Meteor'],
    correctAnswer: 'Constellation',
    explanation: 'A constellation is a group of stars that forms a recognizable pattern in the night sky!',
    funFact: 'The Big Dipper is not actually a constellation - it\'s part of a larger constellation called Ursa Major (the Great Bear)!',
    difficulty: 'easy',
  },
  {
    id: 'science-28',
    category: 'science',
    question: 'Which body part helps you breathe?',
    options: ['Lungs', 'Heart', 'Brain', 'Stomach'],
    correctAnswer: 'Lungs',
    explanation: 'Your lungs help you breathe by taking in oxygen and releasing carbon dioxide!',
    difficulty: 'easy',
  },
  {
    id: 'science-29',
    category: 'science',
    question: 'What is the opposite of magnetic north?',
    options: ['Magnetic South', 'East', 'West', 'Up'],
    correctAnswer: 'Magnetic South',
    explanation: 'Every magnet has two poles: magnetic north and magnetic south!',
    difficulty: 'easy',
  },
  {
    id: 'science-30',
    category: 'science',
    question: 'Which season comes after winter?',
    options: ['Spring', 'Summer', 'Fall', 'Autumn'],
    correctAnswer: 'Spring',
    explanation: 'Spring is the season when plants start growing and flowers bloom!',
    difficulty: 'easy',
  },
  {
    id: 'science-31',
    category: 'science',
    question: 'What do caterpillars turn into?',
    options: ['Butterflies', 'Birds', 'Bees', 'Beetles'],
    correctAnswer: 'Butterflies',
    explanation: 'Caterpillars transform into butterflies through a process called metamorphosis!',
    difficulty: 'easy',
  },
  {
    id: 'science-32',
    category: 'science',
    question: 'Which planet is known as the Blue Planet?',
    options: ['Earth', 'Neptune', 'Uranus', 'Mars'],
    correctAnswer: 'Earth',
    explanation: 'Earth is called the Blue Planet because most of its surface is covered by water!',
    difficulty: 'easy',
  },
  {
    id: 'science-33',
    category: 'science',
    question: 'What is the name of the force that pulls everything toward Earth?',
    options: ['Gravity', 'Magnetism', 'Friction', 'Electricity'],
    correctAnswer: 'Gravity',
    explanation: 'Gravity is the force that keeps us on the ground and makes things fall down!',
    difficulty: 'easy',
  },
  {
    id: 'science-34',
    category: 'science',
    question: 'Which gas do humans breathe out?',
    options: ['Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 'Carbon Dioxide',
    explanation: 'When we breathe out, we release carbon dioxide that plants can use to make food!',
    difficulty: 'easy',
  },

  // Medium Science Questions (33)
  {
    id: 'science-35',
    category: 'science',
    question: 'What is the process by which plants make their own food using sunlight?',
    options: ['Photosynthesis', 'Respiration', 'Digestion', 'Fermentation'],
    correctAnswer: 'Photosynthesis',
    explanation: 'Plants use sunlight, water, and carbon dioxide to create glucose through photosynthesis!',
    difficulty: 'medium',
  },
  {
    id: 'science-36',
    category: 'science',
    question: 'Which of these is NOT a state of matter?',
    options: ['Energy', 'Solid', 'Liquid', 'Gas'],
    correctAnswer: 'Energy',
    explanation: 'The three main states of matter are solid, liquid, and gas. Energy is a form of power!',
    difficulty: 'medium',
  },
  {
    id: 'science-37',
    category: 'science',
    question: 'What is the average human body temperature in Fahrenheit?',
    options: ['98.6', '97.6', '99.6', '96.6'],
    correctAnswer: '98.6',
    explanation: 'The average human body temperature is 98.6°F (37°C)!',
    difficulty: 'medium',
  },
  {
    id: 'science-38',
    category: 'science',
    question: 'What is the name of the force that opposes motion between two surfaces?',
    options: ['Friction', 'Gravity', 'Magnetism', 'Tension'],
    correctAnswer: 'Friction',
    explanation: 'Friction helps us walk, write, and stop when riding a bike!',
    difficulty: 'medium',
  },
  {
    id: 'science-39',
    category: 'science',
    question: 'Which organ pumps blood through your entire body?',
    options: ['Heart', 'Brain', 'Lungs', 'Liver'],
    correctAnswer: 'Heart',
    explanation: 'Your heart pumps about 2,000 gallons of blood through your body every day!',
    difficulty: 'medium',
  },
  {
    id: 'science-40',
    category: 'science',
    question: 'How many chambers does a human heart have?',
    options: ['4', '2', '3', '6'],
    correctAnswer: '4',
    explanation: 'The heart has four chambers: two atria and two ventricles!',
    difficulty: 'medium',
  },
  {
    id: 'science-41',
    category: 'science',
    question: 'What is the process of a solid changing directly into a gas called?',
    options: ['Sublimation', 'Evaporation', 'Condensation', 'Melting'],
    correctAnswer: 'Sublimation',
    explanation: 'Sublimation happens when a solid turns directly into a gas, like dry ice turning into vapor!',
    difficulty: 'medium',
  },
  {
    id: 'science-42',
    category: 'science',
    question: 'Which planet is known as the "Morning Star"?',
    options: ['Venus', 'Mars', 'Mercury', 'Jupiter'],
    correctAnswer: 'Venus',
    explanation: 'Venus is often visible in the morning sky and is called the Morning Star!',
    difficulty: 'medium',
  },
  {
    id: 'science-43',
    category: 'science',
    question: 'What type of energy is stored in food?',
    options: ['Chemical', 'Kinetic', 'Potential', 'Thermal'],
    correctAnswer: 'Chemical',
    explanation: 'Food contains chemical energy that our bodies convert into other forms of energy!',
    difficulty: 'medium',
  },
  {
    id: 'science-44',
    category: 'science',
    question: 'What is the study of fossils called?',
    options: ['Paleontology', 'Archaeology', 'Biology', 'Geology'],
    correctAnswer: 'Paleontology',
    explanation: 'Paleontologists study fossils to learn about ancient life on Earth!',
    difficulty: 'medium',
  },
  {
    id: 'science-45',
    category: 'science',
    question: 'Which element is most abundant in Earth\'s atmosphere?',
    options: ['Nitrogen', 'Oxygen', 'Carbon', 'Hydrogen'],
    correctAnswer: 'Nitrogen',
    explanation: 'Nitrogen makes up about 78% of Earth\'s atmosphere!',
    difficulty: 'medium',
  },
  {
    id: 'science-46',
    category: 'science',
    question: 'What is the speed of sound in miles per hour?',
    options: ['767', '670', '867', '567'],
    correctAnswer: '767',
    explanation: 'Sound travels through air at about 767 miles per hour!',
    difficulty: 'medium',
  },
  {
    id: 'science-47',
    category: 'science',
    question: 'What is the unit of electrical resistance?',
    options: ['Ohm', 'Volt', 'Ampere', 'Watt'],
    correctAnswer: 'Ohm',
    explanation: 'The ohm is named after German physicist Georg Ohm!',
    difficulty: 'medium',
  },
  {
    id: 'science-48',
    category: 'science',
    question: 'Which blood type is known as the universal donor?',
    options: ['O-', 'AB+', 'A+', 'B-'],
    correctAnswer: 'O-',
    explanation: 'O negative blood can be given to patients of all blood types!',
    difficulty: 'medium',
  },
  {
    id: 'science-49',
    category: 'science',
    question: 'What is the study of earthquakes called?',
    options: ['Seismology', 'Geology', 'Geography', 'Meteorology'],
    correctAnswer: 'Seismology',
    explanation: 'Seismologists study earthquakes and the movement of Earth\'s plates!',
    difficulty: 'medium',
  },
  {
    id: 'science-50',
    category: 'science',
    question: 'Which planet has the most visible rings?',
    options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
    correctAnswer: 'Saturn',
    explanation: 'Saturn\'s rings are made mostly of ice and rock particles!',
    difficulty: 'medium',
  },
  {
    id: 'science-51',
    category: 'science',
    question: 'What is the process of plants releasing water vapor called?',
    options: ['Transpiration', 'Respiration', 'Photosynthesis', 'Condensation'],
    correctAnswer: 'Transpiration',
    explanation: 'Plants release water vapor through tiny pores in their leaves!',
    difficulty: 'medium',
  },
  {
    id: 'science-52',
    category: 'science',
    question: 'What is the study of insects called?',
    options: ['Entomology', 'Zoology', 'Biology', 'Ecology'],
    correctAnswer: 'Entomology',
    explanation: 'Entomologists study insects and their relationships with plants, humans, and other animals!',
    difficulty: 'medium',
  },
  {
    id: 'science-53',
    category: 'science',
    question: 'How many pairs of wings do bees have?',
    options: ['2', '1', '3', '4'],
    correctAnswer: '2',
    explanation: 'Bees have two pairs of wings that hook together during flight!',
    difficulty: 'medium',
  },
  {
    id: 'science-54',
    category: 'science',
    question: 'What is the study of the brain called?',
    options: ['Neurology', 'Cardiology', 'Psychology', 'Biology'],
    correctAnswer: 'Neurology',
    explanation: 'Neurologists study the brain and nervous system!',
    difficulty: 'medium',
  },
  {
    id: 'science-55',
    category: 'science',
    question: 'Which element has the chemical symbol Fe?',
    options: ['Iron', 'Gold', 'Silver', 'Copper'],
    correctAnswer: 'Iron',
    explanation: 'Fe comes from the Latin word "ferrum" meaning iron!',
    difficulty: 'medium',
  },
  {
    id: 'science-56',
    category: 'science',
    question: 'What is the largest species of shark?',
    options: ['Whale Shark', 'Great White', 'Tiger Shark', 'Hammerhead'],
    correctAnswer: 'Whale Shark',
    explanation: 'Whale sharks can grow up to 40 feet long!',
    difficulty: 'medium',
  },
  {
    id: 'science-57',
    category: 'science',
    question: 'Which planet is known as the Ice Giant?',
    options: ['Uranus', 'Neptune', 'Saturn', 'Mars'],
    correctAnswer: 'Uranus',
    explanation: 'Uranus is called an Ice Giant because it is made mostly of icy materials!',
    difficulty: 'medium',
  },
  {
    id: 'science-58',
    category: 'science',
    question: 'What is the study of weather called?',
    options: ['Meteorology', 'Geology', 'Biology', 'Astronomy'],
    correctAnswer: 'Meteorology',
    explanation: 'Meteorologists study weather patterns and make forecasts!',
    difficulty: 'medium',
  },
  {
    id: 'science-59',
    category: 'science',
    question: 'Which gas makes up most of the Sun?',
    options: ['Hydrogen', 'Helium', 'Oxygen', 'Nitrogen'],
    correctAnswer: 'Hydrogen',
    explanation: 'The Sun is made up of about 75% hydrogen and 25% helium!',
    difficulty: 'medium',
  },
  {
    id: 'science-60',
    category: 'science',
    question: 'What type of rock is formed by cooled lava?',
    options: ['Igneous', 'Sedimentary', 'Metamorphic', 'Limestone'],
    correctAnswer: 'Igneous',
    explanation: 'Igneous rocks form when hot molten rock (magma or lava) cools and solidifies!',
    difficulty: 'medium',
  },
  {
    id: 'science-61',
    category: 'science',
    question: 'Which part of the cell contains genetic material?',
    options: ['Nucleus', 'Membrane', 'Cytoplasm', 'Mitochondria'],
    correctAnswer: 'Nucleus',
    explanation: 'The nucleus contains DNA, which carries genetic information!',
    difficulty: 'medium',
  },
  {
    id: 'science-62',
    category: 'science',
    question: 'What is the study of plants called?',
    options: ['Botany', 'Zoology', 'Biology', 'Ecology'],
    correctAnswer: 'Botany',
    explanation: 'Botanists study all aspects of plant life!',
    difficulty: 'medium',
  },
  {
    id: 'science-63',
    category: 'science',
    question: 'Which animal has the longest neck?',
    options: ['Giraffe', 'Elephant', 'Ostrich', 'Camel'],
    correctAnswer: 'Giraffe',
    explanation: 'A giraffe\'s neck can be up to 8 feet long!',
    difficulty: 'medium',
  },
  {
    id: 'science-64',
    category: 'science',
    question: 'What is the study of space called?',
    options: ['Astronomy', 'Astrology', 'Geography', 'Geology'],
    correctAnswer: 'Astronomy',
    explanation: 'Astronomers study stars, planets, galaxies, and other objects in space!',
    difficulty: 'medium',
  },
  {
    id: 'science-65',
    category: 'science',
    question: 'Which planet is closest to the Sun?',
    options: ['Mercury', 'Venus', 'Earth', 'Mars'],
    correctAnswer: 'Mercury',
    explanation: 'Mercury orbits closest to the Sun and is also the smallest planet!',
    difficulty: 'medium',
  },
  {
    id: 'science-66',
    category: 'science',
    question: 'What is the smallest unit of life?',
    options: ['Cell', 'Atom', 'Molecule', 'Tissue'],
    correctAnswer: 'Cell',
    explanation: 'Cells are the basic building blocks of all living things!',
    difficulty: 'medium',
  },

  // Hard Science Questions (33)
  {
    id: 'science-67',
    category: 'science',
    question: 'What is the speed of light in miles per second?',
    options: ['186,282', '150,000', '200,000', '175,000'],
    correctAnswer: '186,282',
    explanation: 'Light travels at an incredible speed of 186,282 miles per second!',
    difficulty: 'hard',
  },
  {
    id: 'science-68',
    category: 'science',
    question: 'Which subatomic particle has a negative charge?',
    options: ['Electron', 'Proton', 'Neutron', 'Positron'],
    correctAnswer: 'Electron',
    explanation: 'Electrons are negatively charged particles that orbit the nucleus of an atom!',
    difficulty: 'hard',
  },
  {
    id: 'science-69',
    category: 'science',
    question: 'What is the atomic number of gold?',
    options: ['79', '47', '29', '82'],
    correctAnswer: '79',
    explanation: 'Gold has 79 protons in its nucleus, giving it an atomic number of 79!',
    difficulty: 'hard',
  },
  {
    id: 'science-70',
    category: 'science',
    question: 'What is the pH of a neutral solution?',
    options: ['7', '0', '14', '10'],
    correctAnswer: '7',
    explanation: 'A pH of 7 is neutral, below 7 is acidic, and above 7 is basic!',
    difficulty: 'hard',
  },
  {
    id: 'science-71',
    category: 'science',
    question: 'What is the most abundant element in the universe?',
    options: ['Hydrogen', 'Helium', 'Carbon', 'Oxygen'],
    correctAnswer: 'Hydrogen',
    explanation: 'Hydrogen makes up about 75% of all matter in the universe!',
    difficulty: 'hard',
  },
  {
    id: 'science-72',
    category: 'science',
    question: 'What is the process of nuclear fusion in stars called?',
    options: ['Proton-proton chain', 'Fission', 'Radioactivity', 'Decay'],
    correctAnswer: 'Proton-proton chain',
    explanation: 'The proton-proton chain is how stars like our Sun produce energy!',
    difficulty: 'hard',
  },
  {
    id: 'science-73',
    category: 'science',
    question: 'What is the smallest particle of an element that maintains its properties?',
    options: ['Atom', 'Molecule', 'Cell', 'Electron'],
    correctAnswer: 'Atom',
    explanation: 'An atom is the smallest unit of matter that retains the properties of an element!',
    difficulty: 'hard',
  },
  {
    id: 'science-74',
    category: 'science',
    question: 'What is the process of cell division called?',
    options: ['Mitosis', 'Photosynthesis', 'Respiration', 'Digestion'],
    correctAnswer: 'Mitosis',
    explanation: 'Mitosis is how cells divide to create two identical daughter cells!',
    difficulty: 'hard',
  },
  {
    id: 'science-75',
    category: 'science',
    question: 'What is the unit of force in the metric system?',
    options: ['Newton', 'Joule', 'Watt', 'Pascal'],
    correctAnswer: 'Newton',
    explanation: 'The Newton (N) is named after Sir Isaac Newton and measures force!',
    difficulty: 'hard',
  },
  {
    id: 'science-76',
    category: 'science',
    question: 'What is the chemical formula for table salt?',
    options: ['NaCl', 'H2O', 'CO2', 'O2'],
    correctAnswer: 'NaCl',
    explanation: 'NaCl stands for sodium chloride, which is common table salt!',
    difficulty: 'hard',
  },
  {
    id: 'science-77',
    category: 'science',
    question: 'What is the study of heredity and variation in organisms?',
    options: ['Genetics', 'Biology', 'Chemistry', 'Physics'],
    correctAnswer: 'Genetics',
    explanation: 'Genetics explains how traits are passed from parents to offspring!',
    difficulty: 'hard',
  },
  {
    id: 'science-78',
    category: 'science',
    question: 'What is the largest known galaxy?',
    options: ['IC 1101', 'Milky Way', 'Andromeda', 'Triangulum'],
    correctAnswer: 'IC 1101',
    explanation: 'IC 1101 is about 50 times larger than our Milky Way galaxy!',
    difficulty: 'hard',
  },
  {
    id: 'science-79',
    category: 'science',
    question: 'What is the process of converting sugar into energy called?',
    options: ['Cellular Respiration', 'Photosynthesis', 'Fermentation', 'Digestion'],
    correctAnswer: 'Cellular Respiration',
    explanation: 'Cellular respiration breaks down glucose to produce ATP energy!',
    difficulty: 'hard',
  },
  {
    id: 'science-80',
    category: 'science',
    question: 'What is the study of the interaction between organisms and their environment?',
    options: ['Ecology', 'Biology', 'Zoology', 'Botany'],
    correctAnswer: 'Ecology',
    explanation: 'Ecology studies how living things interact with each other and their environment!',
    difficulty: 'hard',
  },
  {
    id: 'science-81',
    category: 'science',
    question: 'What is the speed of sound in meters per second?',
    options: ['343', '293', '393', '443'],
    correctAnswer: '343',
    explanation: 'Sound travels through air at approximately 343 meters per second at room temperature!',
    difficulty: 'hard',
  },
  {
    id: 'science-82',
    category: 'science',
    question: 'What is the process of rocks changing form due to heat and pressure?',
    options: ['Metamorphism', 'Erosion', 'Weathering', 'Deposition'],
    correctAnswer: 'Metamorphism',
    explanation: 'Metamorphic rocks form when existing rocks are changed by heat and pressure!',
    difficulty: 'hard',
  },
  {
    id: 'science-83',
    category: 'science',
    question: 'What is the study of the Earth\'s atmosphere and weather patterns?',
    options: ['Meteorology', 'Geology', 'Geography', 'Astronomy'],
    correctAnswer: 'Meteorology',
    explanation: 'Meteorologists study weather patterns and make weather forecasts!',
    difficulty: 'hard',
  },
  {
    id: 'science-84',
    category: 'science',
    question: 'What is the process of a liquid changing to a gas at its boiling point?',
    options: ['Vaporization', 'Condensation', 'Sublimation', 'Freezing'],
    correctAnswer: 'Vaporization',
    explanation: 'Vaporization occurs when a liquid reaches its boiling point and becomes a gas!',
    difficulty: 'hard',
  },
  {
    id: 'science-85',
    category: 'science',
    question: 'What is the study of the properties and behavior of light?',
    options: ['Optics', 'Acoustics', 'Mechanics', 'Thermodynamics'],
    correctAnswer: 'Optics',
    explanation: 'Optics includes the study of both visible light and invisible forms of electromagnetic radiation!',
    difficulty: 'hard',
  },
  {
    id: 'science-86',
    category: 'science',
    question: 'What is the process of plants making food called?',
    options: ['Photosynthesis', 'Respiration', 'Digestion', 'Absorption'],
    correctAnswer: 'Photosynthesis',
    explanation: 'Plants use sunlight, water, and carbon dioxide to produce glucose through photosynthesis!',
    difficulty: 'hard',
  },
  {
    id: 'science-87',
    category: 'science',
    question: 'What is the study of the chemical processes in living organisms?',
    options: ['Biochemistry', 'Physics', 'Geology', 'Astronomy'],
    correctAnswer: 'Biochemistry',
    explanation: 'Biochemistry explores the chemical processes essential for life!',
    difficulty: 'hard',
  },
  {
    id: 'science-88',
    category: 'science',
    question: 'What is the smallest unit of digital information?',
    options: ['Bit', 'Byte', 'Kilobyte', 'Megabyte'],
    correctAnswer: 'Bit',
    explanation: 'A bit can have only two values: 0 or 1!',
    difficulty: 'hard',
  },
  {
    id: 'science-89',
    category: 'science',
    question: 'What is the process of DNA making a copy of itself called?',
    options: ['Replication', 'Transcription', 'Translation', 'Mutation'],
    correctAnswer: 'Replication',
    explanation: 'DNA replication ensures that each new cell gets an exact copy of the genetic material!',
    difficulty: 'hard',
  },
  {
    id: 'science-90',
    category: 'science',
    question: 'What is the study of the motion of objects?',
    options: ['Mechanics', 'Thermodynamics', 'Optics', 'Acoustics'],
    correctAnswer: 'Mechanics',
    explanation: 'Mechanics deals with forces and their effects on motion!',
    difficulty: 'hard',
  },
  {
    id: 'science-91',
    category: 'science',
    question: 'What is the process of converting written code into machine language?',
    options: ['Compilation', 'Execution', 'Debugging', 'Testing'],
    correctAnswer: 'Compilation',
    explanation: 'A compiler converts human-readable code into machine-executable instructions!',
    difficulty: 'hard',
  },
  {
    id: 'science-92',
    category: 'science',
    question: 'What is the study of the properties of matter and energy?',
    options: ['Physics', 'Chemistry', 'Biology', 'Geology'],
    correctAnswer: 'Physics',
    explanation: 'Physics explores how the universe behaves at its most fundamental level!',
    difficulty: 'hard',
  },
  {
    id: 'science-93',
    category: 'science',
    question: 'What is the process of rocks breaking down into smaller pieces?',
    options: ['Weathering', 'Erosion', 'Deposition', 'Metamorphism'],
    correctAnswer: 'Weathering',
    explanation: 'Weathering can be caused by both physical and chemical processes!',
    difficulty: 'hard',
  },
  {
    id: 'science-94',
    category: 'science',
    question: 'What is the study of the Earth\'s physical structure and substance?',
    options: ['Geology', 'Geography', 'Meteorology', 'Astronomy'],
    correctAnswer: 'Geology',
    explanation: 'Geologists study rocks, minerals, and the processes that shape the Earth!',
    difficulty: 'hard',
  },
  {
    id: 'science-95',
    category: 'science',
    question: 'What is the process of converting atmospheric nitrogen into a usable form?',
    options: ['Nitrogen Fixation', 'Photosynthesis', 'Respiration', 'Decomposition'],
    correctAnswer: 'Nitrogen Fixation',
    explanation: 'Nitrogen fixation is essential for plants to use nitrogen from the air!',
    difficulty: 'hard',
  },
  {
    id: 'science-96',
    category: 'science',
    question: 'What is the study of the properties and behavior of sound?',
    options: ['Acoustics', 'Optics', 'Mechanics', 'Thermodynamics'],
    correctAnswer: 'Acoustics',
    explanation: 'Acoustics includes the study of sound production, transmission, and effects!',
    difficulty: 'hard',
  },
  {
    id: 'science-97',
    category: 'science',
    question: 'What is the process of converting genetic information from DNA to RNA?',
    options: ['Transcription', 'Translation', 'Replication', 'Mutation'],
    correctAnswer: 'Transcription',
    explanation: 'Transcription is the first step in expressing genetic information!',
    difficulty: 'hard',
  },
  {
    id: 'science-98',
    category: 'science',
    question: 'What is the study of heat and its transformation into other forms of energy?',
    options: ['Thermodynamics', 'Mechanics', 'Optics', 'Acoustics'],
    correctAnswer: 'Thermodynamics',
    explanation: 'Thermodynamics governs how heat behaves and transforms!',
    difficulty: 'hard',
  },
  {
    id: 'science-99',
    category: 'science',
    question: 'What is the process of converting RNA into protein?',
    options: ['Translation', 'Transcription', 'Replication', 'Mutation'],
    correctAnswer: 'Translation',
    explanation: 'Translation is how cells create proteins based on RNA instructions!',
    difficulty: 'hard',
  },
  {
    id: 'science-100',
    category: 'science',
    question: 'What is the process of converting written code into machine language?',
    options: ['Compilation', 'Execution', 'Debugging', 'Testing'],
    correctAnswer: 'Compilation',
    explanation: 'A compiler converts human-readable code into machine-executable instructions!',
    difficulty: 'hard',
  }
]; 