import { Question } from '../types';

export const sportsQuestions: Question[] = [
  // Easy Sports Questions (1-17)
  {
    id: 'sports-1',
    category: 'sports',
    question: 'How many players are on a soccer team during a match?',
    options: ['11', '10', '9', '12'],
    correctAnswer: '11',
    explanation: 'A soccer team has 11 players on the field during a match.',
    difficulty: 'easy',
  },
  {
    id: 'sports-2',
    category: 'sports',
    question: 'In which sport would you perform a slam dunk?',
    options: ['Basketball', 'Football', 'Tennis', 'Soccer'],
    correctAnswer: 'Basketball',
    explanation: 'A slam dunk is when a player jumps and pushes the ball down through the basketball hoop!',
    difficulty: 'easy',
  },
  {
    id: 'sports-3',
    category: 'sports',
    question: 'What color belt is the highest rank in karate?',
    options: ['Black', 'Red', 'White', 'Blue'],
    correctAnswer: 'Black',
    explanation: 'The black belt represents mastery in martial arts!',
    difficulty: 'easy',
  },
  {
    id: 'sports-4',
    category: 'sports',
    question: 'Which game uses a board with black and white squares?',
    options: ['Chess', 'Monopoly', 'Scrabble', 'Snakes and Ladders'],
    correctAnswer: 'Chess',
    explanation: 'Chess is played on a board with 64 black and white squares!',
    difficulty: 'easy',
  },
  {
    id: 'sports-5',
    category: 'sports',
    question: 'What do you hit in tennis?',
    options: ['Ball', 'Puck', 'Stone', 'Disc'],
    correctAnswer: 'Ball',
    explanation: 'In tennis, players hit a small yellow ball back and forth over a net!',
    difficulty: 'easy',
  },
  {
    id: 'sports-6',
    category: 'sports',
    question: 'Which sport uses a bat and ball?',
    options: ['Baseball', 'Soccer', 'Hockey', 'Basketball'],
    correctAnswer: 'Baseball',
    explanation: 'Baseball players use a bat to hit a ball thrown by the pitcher!',
    difficulty: 'easy',
  },
  {
    id: 'sports-7',
    category: 'sports',
    question: 'What do you score in football?',
    options: ['Touchdown', 'Goal', 'Point', 'Basket'],
    correctAnswer: 'Touchdown',
    explanation: 'In football, scoring a touchdown is worth 6 points!',
    difficulty: 'easy',
  },
  {
    id: 'sports-8',
    category: 'sports',
    question: 'Which game uses dice?',
    options: ['Monopoly', 'Chess', 'Go Fish', 'Memory'],
    correctAnswer: 'Monopoly',
    explanation: 'In Monopoly, players roll dice to move around the board!',
    difficulty: 'easy',
  },
  {
    id: 'sports-9',
    category: 'sports',
    question: 'What sport is played on ice with skates?',
    options: ['Hockey', 'Soccer', 'Basketball', 'Baseball'],
    correctAnswer: 'Hockey',
    explanation: 'Hockey players wear skates and play on an ice rink!',
    difficulty: 'easy',
  },
  {
    id: 'sports-10',
    category: 'sports',
    question: 'In which sport do you try to knock down all the pins?',
    options: ['Bowling', 'Golf', 'Tennis', 'Soccer'],
    correctAnswer: 'Bowling',
    explanation: 'In bowling, you roll a ball to knock down 10 pins!',
    difficulty: 'easy',
  },
  {
    id: 'sports-11',
    category: 'sports',
    question: 'What card game has hearts, diamonds, clubs, and spades?',
    options: ['Playing Cards', 'Uno', 'Pokemon', 'Go Fish'],
    correctAnswer: 'Playing Cards',
    explanation: 'A standard deck of playing cards has four suits: hearts, diamonds, clubs, and spades!',
    difficulty: 'easy',
  },
  {
    id: 'sports-12',
    category: 'sports',
    question: 'Which sport uses a racket?',
    options: ['Tennis', 'Soccer', 'Basketball', 'Football'],
    correctAnswer: 'Tennis',
    explanation: 'Tennis players use rackets to hit the ball over the net!',
    difficulty: 'easy',
  },
  {
    id: 'sports-13',
    category: 'sports',
    question: 'What do you kick in soccer?',
    options: ['Ball', 'Puck', 'Stone', 'Disc'],
    correctAnswer: 'Ball',
    explanation: 'In soccer, players kick a round ball to score goals!',
    difficulty: 'easy',
  },
  {
    id: 'sports-14',
    category: 'sports',
    question: 'Which game has red and black checkers?',
    options: ['Checkers', 'Chess', 'Monopoly', 'Sorry'],
    correctAnswer: 'Checkers',
    explanation: 'Checkers is played with red and black pieces called checkers!',
    difficulty: 'easy',
  },
  {
    id: 'sports-15',
    category: 'sports',
    question: 'What do you throw in basketball?',
    options: ['Ball', 'Puck', 'Stone', 'Disc'],
    correctAnswer: 'Ball',
    explanation: 'In basketball, players throw or shoot the ball into the hoop!',
    difficulty: 'easy',
  },
  {
    id: 'sports-16',
    category: 'sports',
    question: 'Which card game do you yell "UNO" in?',
    options: ['Uno', 'Go Fish', 'Crazy Eights', 'Old Maid'],
    correctAnswer: 'Uno',
    explanation: 'In Uno, you must yell "UNO" when you have one card left!',
    difficulty: 'easy',
  },
  {
    id: 'sports-17',
    category: 'sports',
    question: 'What sport uses a small white ball and clubs?',
    options: ['Golf', 'Baseball', 'Tennis', 'Hockey'],
    correctAnswer: 'Golf',
    explanation: 'Golf players use clubs to hit a small white ball into holes!',
    difficulty: 'easy',
  },
  {
    id: 'sports-18',
    category: 'sports',
    question: 'In which game do you try to get four in a row?',
    options: ['Connect Four', 'Tic Tac Toe', 'Checkers', 'Chess'],
    correctAnswer: 'Connect Four',
    explanation: 'In Connect Four, players try to get four discs in a row horizontally, vertically, or diagonally!',
    difficulty: 'easy',
  },
  {
    id: 'sports-19',
    category: 'sports',
    question: 'What color is a standard ping pong ball?',
    options: ['White', 'Yellow', 'Orange', 'Pink'],
    correctAnswer: 'White',
    explanation: 'Standard ping pong balls are white and made of plastic!',
    difficulty: 'easy',
  },
  {
    id: 'sports-20',
    category: 'sports',
    question: 'How many squares are on a chess board?',
    options: ['64', '49', '81', '36'],
    correctAnswer: '64',
    explanation: 'A chess board has 64 squares, arranged in an 8x8 grid!',
    difficulty: 'easy',
  },
  {
    id: 'sports-21',
    category: 'sports',
    question: 'Which sport uses a shuttlecock?',
    options: ['Badminton', 'Tennis', 'Squash', 'Table Tennis'],
    correctAnswer: 'Badminton',
    explanation: 'Badminton players hit a shuttlecock (also called a birdie) over the net!',
    difficulty: 'easy',
  },
  {
    id: 'sports-22',
    category: 'sports',
    question: 'What color are the Olympic rings?',
    options: ['Blue, Yellow, Black, Green, Red', 'Red, Green, Blue, Purple, Orange', 'Yellow, Blue, Red, Green, Brown', 'Black, White, Red, Blue, Green'],
    correctAnswer: 'Blue, Yellow, Black, Green, Red',
    explanation: 'The Olympic rings are blue, yellow, black, green, and red, representing the unity of the five continents!',
    difficulty: 'easy',
  },
  {
    id: 'sports-23',
    category: 'sports',
    question: 'Which game involves matching pairs of cards?',
    options: ['Memory', 'Uno', 'Go Fish', 'Crazy Eights'],
    correctAnswer: 'Memory',
    explanation: 'In Memory (or Concentration), players flip cards to find matching pairs!',
    difficulty: 'easy',
  },
  {
    id: 'sports-24',
    category: 'sports',
    question: 'What do you throw in bowling?',
    options: ['Ball', 'Disc', 'Ring', 'Stone'],
    correctAnswer: 'Ball',
    explanation: 'In bowling, you roll a heavy ball to knock down pins!',
    difficulty: 'easy',
  },
  {
    id: 'sports-25',
    category: 'sports',
    question: 'Which sport uses a net and a court?',
    options: ['Volleyball', 'Hockey', 'Baseball', 'Golf'],
    correctAnswer: 'Volleyball',
    explanation: 'Volleyball is played on a court with a net in the middle!',
    difficulty: 'easy',
  },
  {
    id: 'sports-26',
    category: 'sports',
    question: 'What game uses letter tiles to make words?',
    options: ['Scrabble', 'Monopoly', 'Chess', 'Clue'],
    correctAnswer: 'Scrabble',
    explanation: 'In Scrabble, players use letter tiles to create words and score points!',
    difficulty: 'easy',
  },
  {
    id: 'sports-27',
    category: 'sports',
    question: 'Which sport uses a helmet and pads?',
    options: ['Football', 'Soccer', 'Basketball', 'Tennis'],
    correctAnswer: 'Football',
    explanation: 'Football players wear helmets and pads for protection during the game!',
    difficulty: 'easy',
  },
  {
    id: 'sports-28',
    category: 'sports',
    question: 'What do you roll in dice games?',
    options: ['Dice', 'Ball', 'Wheel', 'Card'],
    correctAnswer: 'Dice',
    explanation: 'Players roll dice to get random numbers in many board games!',
    difficulty: 'easy',
  },
  {
    id: 'sports-29',
    category: 'sports',
    question: 'Which sport uses a yellow ball with red stitches?',
    options: ['Softball', 'Tennis', 'Golf', 'Basketball'],
    correctAnswer: 'Softball',
    explanation: 'A softball is yellow with red stitches and is larger than a baseball!',
    difficulty: 'easy',
  },
  {
    id: 'sports-30',
    category: 'sports',
    question: 'What game uses a spinner and colored spaces?',
    options: ['Twister', 'Chess', 'Checkers', 'Monopoly'],
    correctAnswer: 'Twister',
    explanation: 'In Twister, players spin the spinner to determine which colored spot to place their hands or feet on!',
    difficulty: 'easy',
  },
  {
    id: 'sports-31',
    category: 'sports',
    question: 'Which sport is played in a pool?',
    options: ['Swimming', 'Tennis', 'Soccer', 'Basketball'],
    correctAnswer: 'Swimming',
    explanation: 'Swimming is a sport that takes place in a pool of water!',
    difficulty: 'easy',
  },
  {
    id: 'sports-32',
    category: 'sports',
    question: 'What game involves collecting properties and money?',
    options: ['Monopoly', 'Chess', 'Scrabble', 'Clue'],
    correctAnswer: 'Monopoly',
    explanation: 'In Monopoly, players buy properties and collect rent from other players!',
    difficulty: 'easy',
  },
  {
    id: 'sports-33',
    category: 'sports',
    question: 'Which sport uses a rectangular goal?',
    options: ['Soccer', 'Basketball', 'Tennis', 'Golf'],
    correctAnswer: 'Soccer',
    explanation: 'Soccer players try to kick the ball into a rectangular goal to score points!',
    difficulty: 'easy',
  },
  {
    id: 'sports-34',
    category: 'sports',
    question: 'What game uses a six-sided die?',
    options: ['Yahtzee', 'Chess', 'Cards', 'Dominoes'],
    correctAnswer: 'Yahtzee',
    explanation: 'Yahtzee is played with five six-sided dice!',
    difficulty: 'easy',
  },
  
  // Medium Sports Questions (33)
  {
    id: 'sports-35',
    category: 'sports',
    question: 'How many points is a three-pointer worth in basketball?',
    options: ['3', '2', '4', '1'],
    correctAnswer: '3',
    explanation: 'A shot made from beyond the three-point line is worth 3 points in basketball!',
    difficulty: 'medium',
  },
  {
    id: 'sports-36',
    category: 'sports',
    question: 'What is the maximum number of strokes a golfer can take on a single hole before picking up their ball?',
    options: ['10', '8', '12', '6'],
    correctAnswer: '10',
    explanation: 'Under the maximum score rule in golf, a player must pick up their ball after 10 strokes!',
    difficulty: 'medium',
  },
  {
    id: 'sports-37',
    category: 'sports',
    question: 'In chess, which piece can only move diagonally?',
    options: ['Bishop', 'Knight', 'Rook', 'Queen'],
    correctAnswer: 'Bishop',
    explanation: 'The bishop can only move diagonally across the chess board!',
    difficulty: 'medium',
  },
  {
    id: 'sports-38',
    category: 'sports',
    question: 'How many players are on a volleyball team on the court?',
    options: ['6', '5', '7', '8'],
    correctAnswer: '6',
    explanation: 'A volleyball team has 6 players on the court during a game!',
    difficulty: 'medium',
  },
  {
    id: 'sports-39',
    category: 'sports',
    question: 'What is the standard length of an Olympic swimming pool in meters?',
    options: ['50', '25', '75', '100'],
    correctAnswer: '50',
    explanation: 'An Olympic swimming pool is 50 meters long!',
    difficulty: 'medium',
  },
  {
    id: 'sports-40',
    category: 'sports',
    question: 'In bowling, what is it called when you knock down all pins with two throws?',
    options: ['Spare', 'Strike', 'Split', 'Turkey'],
    correctAnswer: 'Spare',
    explanation: 'A spare is when you knock down all pins using both throws in a frame!',
    difficulty: 'medium',
  },
  {
    id: 'sports-41',
    category: 'sports',
    question: 'How many cards are in a standard deck of playing cards?',
    options: ['52', '48', '54', '50'],
    correctAnswer: '52',
    explanation: 'A standard deck has 52 cards, not counting jokers!',
    difficulty: 'medium',
  },
  {
    id: 'sports-42',
    category: 'sports',
    question: 'What is the diameter of a basketball hoop in inches?',
    options: ['18', '16', '20', '22'],
    correctAnswer: '18',
    explanation: 'A basketball hoop has a diameter of 18 inches!',
    difficulty: 'medium',
  },
  {
    id: 'sports-43',
    category: 'sports',
    question: 'In tennis, what is a score of zero called?',
    options: ['Love', 'Nil', 'Zero', 'Duck'],
    correctAnswer: 'Love',
    explanation: 'In tennis, a score of zero is called "love"!',
    difficulty: 'medium',
  },
  {
    id: 'sports-44',
    category: 'sports',
    question: 'How many pockets are on a standard pool table?',
    options: ['6', '4', '8', '10'],
    correctAnswer: '6',
    explanation: 'A standard pool table has 6 pockets - one in each corner and one in the middle of each long side!',
    difficulty: 'medium',
  },
  {
    id: 'sports-45',
    category: 'sports',
    question: 'What is the standard height of a basketball hoop in feet?',
    options: ['10', '9', '11', '8'],
    correctAnswer: '10',
    explanation: 'A standard basketball hoop is 10 feet (3.05 meters) high!',
    difficulty: 'medium',
  },
  {
    id: 'sports-46',
    category: 'sports',
    question: 'In baseball, how many strikes make an out?',
    options: ['3', '2', '4', '1'],
    correctAnswer: '3',
    explanation: 'A batter is out after three strikes in baseball!',
    difficulty: 'medium',
  },
  {
    id: 'sports-47',
    category: 'sports',
    question: 'How many spaces are there on a Monopoly board?',
    options: ['40', '36', '44', '48'],
    correctAnswer: '40',
    explanation: 'A standard Monopoly board has 40 spaces around the perimeter!',
    difficulty: 'medium',
  },
  {
    id: 'sports-48',
    category: 'sports',
    question: 'What is the maximum number of points possible in a game of Scrabble?',
    options: ['1015', '900', '1200', '850'],
    correctAnswer: '1015',
    explanation: 'The theoretical maximum score in Scrabble is 1015 points!',
    difficulty: 'medium',
  },
  {
    id: 'sports-49',
    category: 'sports',
    question: 'In soccer, how long is each half of the game in minutes?',
    options: ['45', '30', '40', '50'],
    correctAnswer: '45',
    explanation: 'Each half of a soccer game is 45 minutes long!',
    difficulty: 'medium',
  },
  {
    id: 'sports-50',
    category: 'sports',
    question: 'How many different pieces are there in chess (types, not total)?',
    options: ['6', '5', '7', '8'],
    correctAnswer: '6',
    explanation: 'Chess has 6 different types of pieces: pawn, knight, bishop, rook, queen, and king!',
    difficulty: 'medium',
  },
  {
    id: 'sports-51',
    category: 'sports',
    question: 'What is the standard weight of a men\'s shot put in kilograms?',
    options: ['7.26', '6.25', '8.13', '5.44'],
    correctAnswer: '7.26',
    explanation: 'A men\'s shot put weighs 7.26 kilograms (16 pounds)!',
    difficulty: 'medium',
  },
  {
    id: 'sports-52',
    category: 'sports',
    question: 'How many players are on a rugby team during a match?',
    options: ['15', '11', '13', '17'],
    correctAnswer: '15',
    explanation: 'A rugby union team has 15 players on the field during a match!',
    difficulty: 'medium',
  },
  {
    id: 'sports-53',
    category: 'sports',
    question: 'In darts, what is the highest possible score with a single throw?',
    options: ['60', '50', '40', '70'],
    correctAnswer: '60',
    explanation: 'The highest score in darts with one throw is triple 20, which equals 60 points!',
    difficulty: 'medium',
  },
  {
    id: 'sports-54',
    category: 'sports',
    question: 'How many red balls are there in snooker?',
    options: ['15', '10', '12', '8'],
    correctAnswer: '15',
    explanation: 'In snooker, there are 15 red balls worth one point each!',
    difficulty: 'medium',
  },
  {
    id: 'sports-55',
    category: 'sports',
    question: 'What is the standard distance of a marathon in kilometers?',
    options: ['42.2', '40.0', '44.5', '38.6'],
    correctAnswer: '42.2',
    explanation: 'A marathon is 42.2 kilometers (26.2 miles) long!',
    difficulty: 'medium',
  },
  {
    id: 'sports-56',
    category: 'sports',
    question: 'In cricket, how many players are on each team?',
    options: ['11', '9', '13', '15'],
    correctAnswer: '11',
    explanation: 'Each cricket team has 11 players on the field!',
    difficulty: 'medium',
  },
  {
    id: 'sports-57',
    category: 'sports',
    question: 'What is the standard height of a volleyball net in meters for men\'s games?',
    options: ['2.43', '2.24', '2.35', '2.50'],
    correctAnswer: '2.43',
    explanation: 'The men\'s volleyball net height is set at 2.43 meters (7 feet 11 5/8 inches)!',
    difficulty: 'medium',
  },
  {
    id: 'sports-58',
    category: 'sports',
    question: 'How many squares of each color are on a standard chess board?',
    options: ['32', '30', '34', '36'],
    correctAnswer: '32',
    explanation: 'A chess board has 32 white squares and 32 black squares!',
    difficulty: 'medium',
  },
  {
    id: 'sports-59',
    category: 'sports',
    question: 'In bowling, how many pins must you knock down for a strike?',
    options: ['10', '9', '8', '12'],
    correctAnswer: '10',
    explanation: 'A strike in bowling is when all 10 pins are knocked down with the first ball of a frame!',
    difficulty: 'medium',
  },
  {
    id: 'sports-60',
    category: 'sports',
    question: 'What is the standard length of a table tennis table in feet?',
    options: ['9', '8', '10', '7'],
    correctAnswer: '9',
    explanation: 'A standard table tennis table is 9 feet long!',
    difficulty: 'medium',
  },
  {
    id: 'sports-61',
    category: 'sports',
    question: 'How many players are on an ice hockey team during play?',
    options: ['6', '5', '7', '8'],
    correctAnswer: '6',
    explanation: 'An ice hockey team has 6 players on the ice during regular play!',
    difficulty: 'medium',
  },
  {
    id: 'sports-62',
    category: 'sports',
    question: 'In badminton, what is the minimum number of points needed to win a game?',
    options: ['21', '15', '11', '25'],
    correctAnswer: '21',
    explanation: 'A badminton game is won by the first player to reach 21 points (with a 2-point lead)!',
    difficulty: 'medium',
  },
  {
    id: 'sports-63',
    category: 'sports',
    question: 'How many different colors of balls are used in a standard game of pool?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '2',
    explanation: 'Pool uses solid-colored and striped balls, plus the white cue ball and black 8-ball!',
    difficulty: 'medium',
  },
  {
    id: 'sports-64',
    category: 'sports',
    question: 'What is the standard width of a soccer goal in meters?',
    options: ['7.32', '6.50', '8.15', '5.90'],
    correctAnswer: '7.32',
    explanation: 'A standard soccer goal is 7.32 meters (24 feet) wide!',
    difficulty: 'medium',
  },
  {
    id: 'sports-65',
    category: 'sports',
    question: 'In baseball, how many innings are in a standard game?',
    options: ['9', '7', '8', '10'],
    correctAnswer: '9',
    explanation: 'A standard baseball game has 9 innings!',
    difficulty: 'medium',
  },
  {
    id: 'sports-66',
    category: 'sports',
    question: 'How many points is a field goal worth in American football?',
    options: ['3', '2', '4', '6'],
    correctAnswer: '3',
    explanation: 'A successful field goal in American football is worth 3 points!',
    difficulty: 'medium',
  },
  {
    id: 'sports-67',
    category: 'sports',
    question: 'What is the standard weight of a men\'s javelin in kilograms?',
    options: ['0.8', '1.0', '0.6', '1.2'],
    correctAnswer: '0.8',
    explanation: 'A men\'s competition javelin weighs 0.8 kilograms (1.76 pounds)!',
    difficulty: 'medium',
  },

  // Hard Sports Questions (33)
  {
    id: 'sports-68',
    category: 'sports',
    question: 'What is the exact height of a regulation ping pong net in millimeters?',
    options: ['152.5', '150.0', '155.0', '147.5'],
    correctAnswer: '152.5',
    explanation: 'A regulation table tennis net must be exactly 152.5 millimeters (6 inches) high!',
    difficulty: 'hard',
  },
  {
    id: 'sports-69',
    category: 'sports',
    question: 'In professional darts, what is the exact distance from the throwing line to the board in meters?',
    options: ['2.37', '2.44', '2.29', '2.51'],
    correctAnswer: '2.37',
    explanation: 'The throwing line (oche) must be exactly 2.37 meters (7 feet 9.25 inches) from the face of the dartboard!',
    difficulty: 'hard',
  },
  {
    id: 'sports-70',
    category: 'sports',
    question: 'What is the maximum weight allowed for a professional boxing glove in ounces?',
    options: ['12', '10', '14', '16'],
    correctAnswer: '12',
    explanation: 'Professional boxing gloves must not exceed 12 ounces in weight!',
    difficulty: 'hard',
  },
  {
    id: 'sports-71',
    category: 'sports',
    question: 'In professional snooker, what is the exact diameter of a snooker ball in millimeters?',
    options: ['52.5', '51.5', '53.5', '54.5'],
    correctAnswer: '52.5',
    explanation: 'A regulation snooker ball must be exactly 52.5 millimeters in diameter!',
    difficulty: 'hard',
  },
  {
    id: 'sports-72',
    category: 'sports',
    question: 'What is the exact weight of a regulation NFL football in ounces?',
    options: ['14-15', '12-13', '16-17', '13-14'],
    correctAnswer: '14-15',
    explanation: 'An NFL football must weigh between 14 and 15 ounces!',
    difficulty: 'hard',
  },
  {
    id: 'sports-73',
    category: 'sports',
    question: 'In Olympic archery, what is the exact distance to the target in meters?',
    options: ['70', '60', '80', '65'],
    correctAnswer: '70',
    explanation: 'Olympic archers shoot at targets from exactly 70 meters away!',
    difficulty: 'hard',
  },
  {
    id: 'sports-74',
    category: 'sports',
    question: 'What is the exact dimensions of a regulation squash court in meters (length x width)?',
    options: ['9.75 x 6.4', '9.5 x 6.2', '10 x 6.5', '9.25 x 6.1'],
    correctAnswer: '9.75 x 6.4',
    explanation: 'A regulation squash court measures exactly 9.75 meters long by 6.4 meters wide!',
    difficulty: 'hard',
  },
  {
    id: 'sports-75',
    category: 'sports',
    question: 'In professional cricket, what is the exact length of the pitch in yards?',
    options: ['22', '20', '24', '26'],
    correctAnswer: '22',
    explanation: 'A cricket pitch is exactly 22 yards (20.12 meters) long!',
    difficulty: 'hard',
  },
  {
    id: 'sports-76',
    category: 'sports',
    question: 'What is the exact weight of a regulation tennis ball in grams?',
    options: ['56.7-58.5', '55.0-57.0', '58.5-60.0', '54.0-56.0'],
    correctAnswer: '56.7-58.5',
    explanation: 'A regulation tennis ball must weigh between 56.7 and 58.5 grams!',
    difficulty: 'hard',
  },
  {
    id: 'sports-77',
    category: 'sports',
    question: 'In Olympic weightlifting, what is the diameter of a regulation barbell in millimeters?',
    options: ['28', '25', '30', '32'],
    correctAnswer: '28',
    explanation: 'An Olympic weightlifting barbell must be exactly 28 millimeters in diameter!',
    difficulty: 'hard',
  },
  {
    id: 'sports-78',
    category: 'sports',
    question: 'What is the exact height of a regulation volleyball net for women\'s games in meters?',
    options: ['2.24', '2.20', '2.28', '2.32'],
    correctAnswer: '2.24',
    explanation: 'The women\'s volleyball net height must be exactly 2.24 meters (7 feet 4 1/8 inches)!',
    difficulty: 'hard',
  },
  {
    id: 'sports-79',
    category: 'sports',
    question: 'In professional golf, what is the exact diameter of a golf hole in inches?',
    options: ['4.25', '4.00', '4.50', '4.75'],
    correctAnswer: '4.25',
    explanation: 'A regulation golf hole must be exactly 4.25 inches (108 millimeters) in diameter!',
    difficulty: 'hard',
  },
  {
    id: 'sports-80',
    category: 'sports',
    question: 'What is the exact circumference of a regulation NBA basketball in inches?',
    options: ['29.5', '28.5', '30.5', '27.5'],
    correctAnswer: '29.5',
    explanation: 'An NBA basketball must have a circumference of exactly 29.5 inches!',
    difficulty: 'hard',
  },
  {
    id: 'sports-81',
    category: 'sports',
    question: 'In Olympic swimming, what is the minimum depth of the pool in meters?',
    options: ['2.0', '1.8', '2.2', '1.6'],
    correctAnswer: '2.0',
    explanation: 'An Olympic swimming pool must be at least 2.0 meters deep!',
    difficulty: 'hard',
  },
  {
    id: 'sports-82',
    category: 'sports',
    question: 'What is the exact weight of a regulation field hockey ball in grams?',
    options: ['156-163', '150-157', '160-167', '153-160'],
    correctAnswer: '156-163',
    explanation: 'A field hockey ball must weigh between 156 and 163 grams!',
    difficulty: 'hard',
  },
  {
    id: 'sports-83',
    category: 'sports',
    question: 'In professional badminton, what is the exact number of feathers required in a regulation shuttlecock?',
    options: ['16', '14', '18', '20'],
    correctAnswer: '16',
    explanation: 'A regulation badminton shuttlecock must have exactly 16 feathers!',
    difficulty: 'hard',
  },
  {
    id: 'sports-84',
    category: 'sports',
    question: 'What is the exact height of a regulation hurdle for men\'s 110m hurdles in meters?',
    options: ['1.067', '1.000', '1.125', '0.950'],
    correctAnswer: '1.067',
    explanation: 'Men\'s 110m hurdles must be exactly 1.067 meters (3 feet 6 inches) high!',
    difficulty: 'hard',
  },
  {
    id: 'sports-85',
    category: 'sports',
    question: 'What is the exact weight of a regulation javelin for women\'s competition in grams?',
    options: ['600', '500', '700', '800'],
    correctAnswer: '600',
    explanation: 'A women\'s competition javelin must weigh exactly 600 grams!',
    difficulty: 'hard',
  },
  {
    id: 'sports-86',
    category: 'sports',
    question: 'In professional table tennis, what is the exact height the ball must be tossed for a legal serve in centimeters?',
    options: ['16', '14', '18', '20'],
    correctAnswer: '16',
    explanation: 'In table tennis, the ball must be tossed at least 16 centimeters high for a legal serve!',
    difficulty: 'hard',
  },
  {
    id: 'sports-87',
    category: 'sports',
    question: 'What is the exact distance between bases in Major League Baseball in feet?',
    options: ['90', '85', '95', '88'],
    correctAnswer: '90',
    explanation: 'The distance between bases in MLB is exactly 90 feet (27.4 meters)!',
    difficulty: 'hard',
  },
  {
    id: 'sports-88',
    category: 'sports',
    question: 'In professional rugby, what is the exact width of the goal posts in meters?',
    options: ['5.6', '5.4', '5.8', '6.0'],
    correctAnswer: '5.6',
    explanation: 'Rugby goal posts are exactly 5.6 meters (18 feet 4 inches) wide!',
    difficulty: 'hard',
  },
  {
    id: 'sports-89',
    category: 'sports',
    question: 'What is the exact weight of a regulation discus for men\'s competition in kilograms?',
    options: ['2', '1.5', '2.5', '3'],
    correctAnswer: '2',
    explanation: 'A men\'s competition discus must weigh exactly 2 kilograms!',
    difficulty: 'hard',
  },
  {
    id: 'sports-90',
    category: 'sports',
    question: 'In Olympic diving, what is the exact water temperature requirement in degrees Celsius?',
    options: ['26', '24', '28', '30'],
    correctAnswer: '26',
    explanation: 'Olympic diving pools must maintain a temperature of 26 degrees Celsius!',
    difficulty: 'hard',
  },
  {
    id: 'sports-91',
    category: 'sports',
    question: 'What is the exact height of a regulation basketball backboard in inches?',
    options: ['42', '40', '44', '46'],
    correctAnswer: '42',
    explanation: 'A regulation basketball backboard must be exactly 42 inches (106.7 cm) high!',
    difficulty: 'hard',
  },
  {
    id: 'sports-92',
    category: 'sports',
    question: 'In professional boxing, what is the exact size of the ring in feet?',
    options: ['20', '18', '22', '24'],
    correctAnswer: '20',
    explanation: 'A professional boxing ring must be 20 feet by 20 feet inside the ropes!',
    difficulty: 'hard',
  },
  {
    id: 'sports-93',
    category: 'sports',
    question: 'What is the exact weight of a regulation soccer ball in grams?',
    options: ['410-450', '400-440', '420-460', '430-470'],
    correctAnswer: '410-450',
    explanation: 'A regulation soccer ball must weigh between 410 and 450 grams!',
    difficulty: 'hard',
  },
  {
    id: 'sports-94',
    category: 'sports',
    question: 'In Olympic weightlifting, what is the exact width between the inner collars of a barbell in millimeters?',
    options: ['1310', '1300', '1320', '1330'],
    correctAnswer: '1310',
    explanation: 'The distance between inner collars on an Olympic barbell is exactly 1310 millimeters!',
    difficulty: 'hard',
  },
  {
    id: 'sports-95',
    category: 'sports',
    question: 'What is the exact height of a regulation beach volleyball net for mixed competition in meters?',
    options: ['2.34', '2.32', '2.36', '2.38'],
    correctAnswer: '2.34',
    explanation: 'A beach volleyball net for mixed competition must be exactly 2.34 meters high!',
    difficulty: 'hard',
  },
  {
    id: 'sports-96',
    category: 'sports',
    question: 'In professional darts, what is the exact height of the bullseye center from the floor in centimeters?',
    options: ['173', '170', '175', '178'],
    correctAnswer: '173',
    explanation: 'The center of the dartboard bullseye must be exactly 173 centimeters from the floor!',
    difficulty: 'hard',
  },
  {
    id: 'sports-97',
    category: 'sports',
    question: 'What is the exact diameter of a regulation water polo goal in meters?',
    options: ['3', '2.8', '3.2', '2.6'],
    correctAnswer: '3',
    explanation: 'A water polo goal must be exactly 3 meters wide!',
    difficulty: 'hard',
  },
  {
    id: 'sports-98',
    category: 'sports',
    question: 'In professional ice hockey, what is the exact thickness of the ice in inches?',
    options: ['3/4', '1', '1/2', '5/8'],
    correctAnswer: '3/4',
    explanation: 'Professional ice hockey rinks must maintain ice thickness of exactly 3/4 inch!',
    difficulty: 'hard',
  },
  {
    id: 'sports-99',
    category: 'sports',
    question: 'What is the exact weight of a regulation men\'s hammer throw in kilograms?',
    options: ['7.26', '7.00', '7.50', '6.75'],
    correctAnswer: '7.26',
    explanation: 'A men\'s competition hammer must weigh exactly 7.26 kilograms (16 pounds)!',
    difficulty: 'hard',
  },
  {
    id: 'sports-100',
    category: 'sports',
    question: 'In Olympic fencing, what is the exact length of an épée blade in centimeters?',
    options: ['90', '88', '92', '86'],
    correctAnswer: '90',
    explanation: 'An Olympic épée blade must be exactly 90 centimeters long!',
    difficulty: 'hard',
  }
]; 